---
title: "PSF Greenhouse: Biomass Plots"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in data
```{r, message = F}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(plotrix)

# Set working directory to Google Drive
PSF <- Sys.getenv("PSF")

# Read in data
biomass <- read.csv(file.path(PSF, "/data/L1/psf_biomass_2021_L1.csv"))

str(biomass)
```

Total Biomass
```{r}
# first by block
avg_total_biomass <- biomass %>%
        group_by(treatment, species, block) %>%
        summarize(avg_biomass = mean(total_biomass, na.rm = TRUE),
            se = std.error(total_biomass, na.rm = TRUE))
# then average over blocks
avg_total_biomass2 <- avg_total_biomass %>%
        group_by(treatment, species) %>%
        summarize(average_biomass = mean(avg_biomass, na.rm = TRUE),
            se = std.error(avg_biomass, na.rm = TRUE))

# plot
total <- ggplot(avg_total_biomass2, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        facet_wrap(.~species, 
                   scales = "free") +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Biomass (g)", title = "Average Total Biomass") +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W", "control" = "C")) +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
```

Aboveground Biomass
```{r}
# first by block
avg_above <- biomass %>%
        group_by(treatment, species, block) %>%
        summarize(avg_biomass = mean(biomass_above, na.rm = TRUE),
            se = std.error(biomass_above, na.rm = TRUE))
# then average over blocks
avg_above_biomass2 <- avg_above %>%
        group_by(treatment, species) %>%
        summarize(average_biomass = mean(avg_biomass, na.rm = TRUE),
            se = std.error(avg_biomass, na.rm = TRUE))

# plot
above <- ggplot(avg_above_biomass2, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        facet_wrap(.~species, 
                   scales = "free") +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Biomass (g)", title = "Average Aboveground Biomass") +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W", "control" = "C")) +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
```

Belowground Biomass
```{r}
# first by block
avg_below <- biomass %>%
        group_by(treatment, species, block) %>%
        summarize(avg_biomass = mean(biomass_below, na.rm = TRUE),
            se = std.error(biomass_below, na.rm = TRUE))
# then average over blocks
avg_below_biomass2 <- avg_below %>%
        group_by(treatment, species) %>%
        summarize(average_biomass = mean(avg_biomass, na.rm = TRUE),
            se = std.error(avg_biomass, na.rm = TRUE))

# plot
below <- ggplot(avg_below_biomass2, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        facet_wrap(.~species, 
                   scales = "free") +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Biomass (g)", title = "Average Belowground Biomass") +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W", "control" = "C")) +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
below
```

Combine graphs above into one figure
```{r}
total2 <- total + labs(x = NULL)
below2 <- below + labs(y = NULL, x = NULL)
above2 <- above + labs(y = NULL, x = NULL)

biomass_plot <- ggpubr::ggarrange(total2, above2, below2,
                          nrow = 1, ncol = 3, legend = "none")

png("psf_biomass_bar_plots_L2.png", units="in", width=12, height=6, res=300)
biomass_plot
dev.off()
```

Red clover only
```{r}
red_clover_total <- avg_total_biomass2[which(avg_total_biomass2$species == "Trpr"),]
red_clover_above <- avg_above_biomass2[which(avg_above_biomass2$species == "Trpr"),]
red_clover_below <- avg_below_biomass2[which(avg_below_biomass2$species == "Trpr"),]

trpr_total <- ggplot(red_clover_total, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Average Biomass (g)", title = "Total") +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed", "control" = "Control"))  +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
trpr_total

trpr_above <- ggplot(red_clover_above, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Average Biomass (g)", title = "Aboveground") +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed", "control" = "Control"))  +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
trpr_above

trpr_below <- ggplot(red_clover_below, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Average Biomass (g)", title = "Belowground") +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed", "control" = "Control")) +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
trpr_below

trpr_total2 <- trpr_total + labs(x = NULL)
trpr_below2 <- trpr_below + labs(y = NULL, x = NULL)
trpr_above2 <- trpr_above + labs(y = NULL, x = NULL)

trpr_biomass_plot <- ggpubr::ggarrange(trpr_total2, trpr_above2, trpr_below2,
                          nrow = 1, ncol = 3, legend = "none")

png("psf_trpr_biomass_bar_plots_L2.png", units="in", width=10, height=6, res=300)
trpr_biomass_plot
dev.off()
```

Red clover only without greenhouse control
```{r}
red_clover_total1 <- red_clover_total[-which(red_clover_total$treatment == "control"),]
red_clover_above1 <- red_clover_above[-which(red_clover_above$treatment == "control"),]
red_clover_below1 <- red_clover_below[-which(red_clover_below$treatment == "control"),]

trpr_total <- ggplot(red_clover_total1, aes(x=factor(treatment, level=c('ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Average Biomass (g)", title = "Total") +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed"))  +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick"))
trpr_total

trpr_above <- ggplot(red_clover_above1, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Average Biomass (g)", title = "Aboveground") +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed", "control" = "Control"))  +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
trpr_above

trpr_below <- ggplot(red_clover_below1, aes(x=factor(treatment, level=c('control', 'ambient', 'warmed')), y = average_biomass, fill = treatment)) +
        geom_bar(position = "identity", stat = "identity") +
        geom_errorbar(aes(ymin = average_biomass - se, ymax = average_biomass + se), width = 0.2, position = "identity") +
        labs(x = "Treatment", y = "Average Biomass (g)", title = "Belowground") +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed", "control" = "Control")) +
        scale_fill_manual(values = c("ambient" = "deepskyblue", "warmed" = "firebrick", "control" = "goldenrod"))
trpr_below

trpr_total2 <- trpr_total + labs(x = NULL)
trpr_below2 <- trpr_below + labs(y = NULL, x = NULL)
trpr_above2 <- trpr_above + labs(y = NULL, x = NULL)

trpr_biomass_plot <- ggpubr::ggarrange(trpr_total2, trpr_above2, trpr_below2,
                          nrow = 1, ncol = 3, legend = "none")

png("psf_trpr_biomass_bar_plots_L2.png", units="in", width=8, height=6, res=300)
trpr_biomass_plot
dev.off()
```

