---
title: "warmXtrophic project: Phenology Analysis"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

# Script Details:
```{r, message = F}
script_tbl <- data.frame(
  Item = c("OVERVIEW", "COLLABORATORS", "REQUIRES", "DATA INPUT", "DATA OUTPUT", "NOTES"),
  Details = c("This script explores and analyses the flower and seed phenolgy data from the KBS and UMBS stations. Flowering and seeding was recorded as species present with at least one individual flowering every 3 days in the beginning of the field season and continued to be measured until the end of the field season. For calculating phenology dates, we calculated the date of first flower, median flower date, and average duration of flowering. For seeding with calculated the date of first seed",
              "Phoebe, Zarnetske, Kara Dobson, Mark Hammond, Pat Bills",
              "Prior to running this script, make sure phenology_clean_L0.R is run and up to date. That script creates the final_phenology_L1.csv in the L1 folder in the Google drive, which contains the clean phenology data",
              "Data imported as csv files from shared Google drive 'SpaCE_Lab_warmXtrophic' phenology folder",
              "... a brief description of the data output from through the script, including what format it’s in",
              "Each row in 'phen_data' is a date at which flowering or seeding was recorded, per species. The 'phen_kbs' and 'phen_umbs' dataframes contain data for phenolgy at each site."
  )
)

kbl(script_tbl) %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, width = "30em", background = "lightblue")

# will update this to reflect phenology data frames
metadata_tbl <- data.frame(
  Variable = c("spp_half_cover_date", "plot_half_cover_date", "state"),
  Definition = c("date at which 50% of a species max cover was reached (per species, per plot, per year)", 
    "the date at which 50% of a plot's max cover was reached (per plot, per year)",
    "describes each treatment: warmed or ambient"
  )
)

kbl(metadata_tbl) %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, width = "30em", background = "lightyellow")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Clear existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(ggplot2)
library(lme4)
library(lmerTest)
library(emmeans)
library(vegan)
library(car)
library(rstatix)
library(scales)
library(fitdistrplus)
library(moments)# for calculating skewness of data
library(ggpubr)
library(jtools) # summ() function
library(predictmeans)
library(olsrr)
library(car)
library(fitdistrplus)
library(ggpubr)
library(interactions)
library(sjPlot)
library(effects)
library(glmmTMB)

# Set working directory to Google Drive
setwd("/Volumes/GoogleDrive/Shared drives/SpaCE_Lab_warmXtrophic/data/")

# Read in data
# cleaned phenology data from L1
phen_data <- read.csv("/Volumes/GoogleDrive/Shared drives/SpaCE_Lab_warmXtrophic/data/L1/phenology/final_flw_sd_L1.csv", stringsAsFactors=FALSE)
phen_data$X <- NULL # get rid of "X" column that shows up
View(phen_data) # take a look at the data to see if looks good

# Order warm and ambient so that warm shows up first in plotting (and is default is red = warm; blue = ambient). First make it a factor.
# greenup$state = with(greenup, reorder(class, hwy, median))

phen_data$state<-as.factor(phen_data$state)
levels(phen_data$state)
phen_data$state <- factor(phen_data$state, levels(phen_data$state)[c(2,1)])
levels(phen_data$state)

# make a column that breaks down years as 1, 2, 3, 4, 5, 6 and into factors
phen_data$year_factor <- 
        ifelse(phen_data$year == 2015, "1",
               ifelse(phen_data$year == 2016, "2",
                      ifelse(phen_data$year == 2017, "3",
                             ifelse(phen_data$year == 2018, "4",
                                    ifelse(phen_data$year == 2019, "5",
                                           ifelse(phen_data$year == 2020, "6", NA))))))

# Create separate data frames for flowering and seeding
phen_flwr <- subset(phen_data, action == "flower")
phen_sd <- subset(phen_data, action == "seed")

# Separate data frame by site for flower
kbs_flwr <- subset(phen_flwr, site == "kbs")
umbs_flwr <- subset(phen_flwr, site == "umbs")

# Separate data frame by site for seed set
kbs_sd <- subset(phen_sd, site == "kbs")
umbs_sd <- subset(phen_sd, site == "umbs")

# First Flower by species level - filter data to contain the date of first flower for each species at each plot
FirstFlwr_spp <- phen_flwr %>%
        group_by(plot, year, species, state, site, action, origin, insecticide, year_factor) %>%
        summarize(julian = min(julian, na.rm=T))

# First Flower Date by plot level
FirstFlwr_plot <- phen_flwr %>%
        group_by(plot, year, state, site, insecticide, year_factor) %>%
        summarize(julian = min(julian, na.rm=T))

# Median Flower Date by species level - filter data to contain the median date of flower for each species at each plot
MedianFlwr_spp <- phen_flwr %>%
        group_by(plot, year, species, state, site, action, origin, insecticide, year_factor, treatment_key) %>%
        summarize(julian = median(julian, na.rm=T))

# Median Flower Date by plot level
MedianFlwr_plot <- phen_flwr %>%
        group_by(plot, year, state, site, insecticide, year_factor) %>%
        summarize(julian = min(julian, na.rm=T))
```

# Data Exploration: are there differences between warmed vs. ambient plots when we account for species?
# *Starting with UMBS*

First Flower
```{r}
umbs_firstflwr_spp <- subset(FirstFlwr_spp, site == "umbs") # pull out umbs only data

umbs_firstflwr_plot <- subset(FirstFlwr_plot, site == "umbs") # pull out umbs only data

# first flower
hist(umbs_firstflwr_spp$julian) # poisson?
qqnorm(umbs_firstflwr_spp$julian)
fit1 <- lm(julian ~ state, data = umbs_firstflwr_spp)
qqPlot(fit1)
shapiro.test(umbs_firstflwr_spp$julian) 

descdist(umbs_firstflwr_spp$julian, discrete = FALSE) # uniform? normal?

skewness(umbs_firstflwr_spp$julian)

umbs_firstflwr_spp$sqrt_julian <- sqrt(umbs_firstflwr_spp$julian)
hist(umbs_firstflwr_spp$sqrt_julian)
skewness(umbs_firstflwr_spp$sqrt_julian, na.rm = TRUE)
```

Median Flower 
```{r}
umbs_medflwr_spp <- subset(MedianFlwr_spp, site == "umbs") # pull out umbs only data

umbs_medflwr_plot <- subset(MedianFlwr_spp, site == "umbs") # pull out umbs only data

hist(umbs_medflwr_spp$julian)
#explore what's going on around julian date 190

umbs_flwr_explore <- subset(umbs_medflwr_spp, julian > 190)
View(umbs_flwr_explore) 
# I'm not really seeing anything glaring here when I look at the data. Cest is the most dominate species it
# appears. I'm going to pull out all the Cest data and look at it separately. 

umbs_flwr_cest <- subset(umbs_medflwr_spp, species == "Cest") #just Cest median flower date
View(umbs_flwr_cest)
hist(umbs_flwr_cest$julian) # this looks pretty normal to me - slight left skew in the data

# Looking into making early and late flowering categories for species (make new column)
umbs_median_species <- umbs_flwr %>% #median date of flower for each species across EVERYTHING at umbs
        group_by(species) %>%
        summarize(julian = median(julian, na.rm=T))
View(umbs_median_species)
summary(umbs_median_species) # Mean = 183.2 

# Not sure if this is the best way to do this, but I calculated the median date of flower for each species 
# across all years and plots then took the summary of those median dates, took the mean (183.2) and made a
# new column for a flower group broken into "early" (species with a median date less than 183) and "late" 
# (species with a median date greater than 183) median flower date. 
umbs_median_species$flwr_group <- with(umbs_median_species, 
                                       ifelse(julian >= 183, "late", "early"))
View(umbs_median_species)
# "early" species: Acru, Ansp, Cape, Dasp, Frve, Hiau, Hica, Hipi, Hisp, Poco, Popr, Ruac, Rual, Spsp, Trdu, Unknown, Vaan, Vear
# "late" species: Anma, Apan, Assy, Asun, Cest, Elre, Gnul, Hype, Sogi, Sone, Sohi, Syla

umbs_flwr_med$flwr_group <- with(umbs_flwr_med, 
                                       ifelse(species == c("Acru", "Ansp", "Cape", "Dasp", "Frve", "Hiau", "Hica", "Hipi", "Hisp", "Poco", "Popr", "Ruac", "Rual", "Spsp", "Trdu", "Unknown", "Vaan", "Vear"), "early", "late"))

# histograms for both "early" and "late" flower group separately 
hist(umbs_flwr_med$julian[umbs_flwr_med$flwr_group == "early"])
hist(umbs_flwr_med$julian[umbs_flwr_med$flwr_group == "late"])
# I don't think this did what I wanted it too..... I need a break.



qqnorm(umbs_medflwr_spp$julian)
fit2 <- lm(julian ~ state, data = umbs_flwr_med)
qqPlot(fit2)
shapiro.test(umbs_medflwr_spp$julian)

descdist(umbs_medflwr_spp$julian, discrete = FALSE) # uniform?

skewness(umbs_medflwr_spp$julian, na.rm = TRUE)  # slight positive skew

# Because of slight positive skew I'm transforming the data by taking the square root.
umbs_medflwr_spp$sqrt_julian <- sqrt(umbs_medflwr_spp$julian) 
hist(umbs_medflwr_spp$sqrt_julian)
skewness(umbs_medflwr_spp$sqrt_julian, na.rm = TRUE)

ggdensity(umbs_medflwr_spp, x = "sqrt_julian", fill = "lightgray", title = "CONT") +
        stat_overlay_normal_density(color = "red", linetype = "dashed") 
# there's that weird dip around 14 on the x-axis
```

Models!
What is the effect of warming (state) on the median date of flower?
```{r}
# Models using median flowering julian date

# Null model?
model0 <- lmer(sqrt_julian ~ 1 # This means median flower date (julian) is predicted by the intercept
               + (1|plot), data = umbs_flwr_med, REML=FALSE) # each plot gets its own intercept?
summary(model0) 

# The effects of warming/ambient (state) on median date of flowering (julian) with species (species) as a random effect.
model1 <- lmer(sqrt_julian ~ state + (1|species), data = umbs_flwr_med, REML=FALSE)
summary(model1)

# The effects of warming/ambient on median date of flowering (julian - response variable) with an interaction between warming and native vs exotic species (origin) with species and year as a random effect.
model2 <- lmer(sqrt_julian ~ state*origin + (1|species) + (1|year_factor), data = umbs_flwr_med, REML=FALSE)
summary(model2)

# The effects of warming/ambient on median date of flowering with origin and insecticide as fixed effects and species and year_factor as random effects
model3 <- lmer(sqrt_julian ~ state + origin + insecticide + (1|species) + (1|year_factor), data = umbs_flwr_med, REML=FALSE)
summary(model3)
summ(model3)
```

Permanova
```{r}
#perma1 <- adonis2(julian ~ state + (1|species), data = umbs_flwr_med, permutations = 999, by = "terms")
#summary(perma1)

permanova.lmer(model1)
```

Updated from Kileigh's script
```{r, warning=FALSE}
#should plot be a random effect?
moda <- lmer(sqrt_julian ~ state*origin + insecticide + (1|species) + (1|plot), umbs_flwr_med, REML=FALSE)
mod1 <- lmer(sqrt_julian ~ state*origin + insecticide + (1|species), umbs_flwr_med, REML=FALSE)
anova(mod1,moda)
AIC(mod1, moda)

#Do we need insects?
mod2 <- lmer(sqrt_julian ~ state*origin + (1|species), umbs_flwr_med, REML=FALSE)
anova(mod2,mod1)

#Do we need interaction term?
mod3 <- lmer(sqrt_julian ~ state + origin + (1|species), umbs_flwr_med, REML=FALSE)
anova(mod3, mod2)
anova(mod3)
summary(mod3)
confint(mod3, method="boot", nsim=999)
difflsmeans(mod3, test.effs=NULL, ddf="Satterthwaite")
```

## KBS Data

```{r}
kbs_firstflwr <- subset(FirstFlower_all, site == "kbs") # pull out kbs only data

kbs_flwr_med <- subset(MedianFlwr_all, site == "kbs") # pull out kbs only data

hist(kbs_flwr_med$julian)
qqnorm(kbs_flwr_med$julian)
fit2 <- lm(julian ~ state, data = umbs_flwr_med)
qqPlot(fit2)
shapiro.test(kbs_flwr_med$julian) #not normal

descdist(kbs_flwr_med$julian, discrete = FALSE) # beta?

skewness(kbs_flwr_med$julian, na.rm = TRUE)  # slight positive skew

ggdensity(kbs_flwr_med, x = "julian", fill = "lightgray", title = "CONT") +
        stat_overlay_normal_density(color = "red", linetype = "dashed") 

# Because of positive skew I'm transforming the data by taking the square root
kbs_flwr_med$sqrt_julian <- sqrt(kbs_flwr_med$julian) 
hist(kbs_flwr_med$sqrt_julian)
skewness(kbs_flwr_med$sqrt_julian, na.rm = TRUE)

# Now try the log of julian dates
kbs_flwr_med$log_julian <- log10(kbs_flwr_med$julian)
hist(kbs_flwr_med$log_julian)
skewness(kbs_flwr_med$log_julian, na.rm = TRUE)

# Ok now try the inverse
kbs_flwr_med$inv_julian <- 1/(kbs_flwr_med$julian)
hist(kbs_flwr_med$inv_julian)
skewness(kbs_flwr_med$inv_julian, na.rm = TRUE) 
#taking the inverse of the julian dates made the data the least skewed
qqnorm(kbs_flwr_med$inv_julian)
shapiro.test(kbs_flwr_med$inv_julian) #still not normal

#pois <- glm(julian ~ state, data = kbs_flwr_med, family="poisson")
#hist(pois$residuals)
```

