---
title: "Biomass Plots"
author: "Kara Dobson"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TITLE:          Biomass plots  
## AUTHORS:        Kara Dobson  
## COLLABORATORS:  Phoebe Zarnetske, Moriah Young, Mark Hammond, Pat Bills  
## DATA INPUT:     Data imported as csv files from shared Google drive L0 folder  
## DATA OUTPUT:    Visualizations of biomass data  
## PROJECT:        warmXtrophic  
## DATE:           March 2022  

```{r}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(plotrix)
library(ggpubr)
library(emmeans)

# Get data
Sys.getenv("L1DIR")
L1_dir<-Sys.getenv("L1DIR")
list.files(L1_dir)
kbs_biomass_21 <- read.csv(file.path(L1_dir, "ANPP/kbs_biomass_2021_L1.csv"))
umbs_biomass_21 <- read.csv(file.path(L1_dir, "ANPP/umbs_biomass_2021_L1.csv"))
kbs_biomass_21 <- kbs_biomass_21 %>% dplyr::select(-X) # get rid of "X" column that shows up (could fix this in cleaning script)
umbs_biomass_21 <- umbs_biomass_21 %>% dplyr::select(-X)

# making separate dataframe for biomass - easier in plots
kbs_biomass_only <- kbs_biomass_21 %>%
        select(-cover) %>%
        drop_na(weight_g)
umbs_biomass_only <- umbs_biomass_21 %>%
        select(-cover) %>%
        drop_na(weight_g)

# remove uninformative species
kbs_biomass_live <- kbs_biomass_only[!grepl("Litter", kbs_biomass_only$species),]
kbs_biomass_live <- kbs_biomass_live[!grepl("Umsp", kbs_biomass_live$species),]
umbs_biomass_live <- umbs_biomass_only[!grepl("Litter", umbs_biomass_only$species),]
umbs_biomass_live <- umbs_biomass_live[!grepl("Standing_Dead", umbs_biomass_live$species),]
umbs_biomass_live <- umbs_biomass_live[!grepl("Surface_Litter", umbs_biomass_live$species),]
umbs_biomass_live <- umbs_biomass_live[!grepl("Lisp", umbs_biomass_live$species),]
umbs_biomass_live <- umbs_biomass_live[!grepl("Umsp", umbs_biomass_live$species),]

# keeping species found only in w and a
kbs_biomass_live2 <- kbs_biomass_live %>%
        group_by(species) %>% 
        filter(all(c('warmed', 'ambient') %in% state))
umbs_biomass_live2 <- umbs_biomass_live %>%
        group_by(species) %>% 
        filter(all(c('warmed', 'ambient') %in% state))

# clean insecticide labels for plotting
insect_labels <- c("insects" = "Herbivory", "no_insects" = "Reduced Herbivory")



### Overall averages btwn treatments - barplot
# plot level KBS
biomass_sum_k2 <- kbs_biomass_live %>%
        group_by(plot, state, insecticide) %>%
        summarize(avg_weight = sum(weight_g, na.rm = TRUE))
biomass_sum_k3 <- biomass_sum_k2 %>%
        group_by(state, insecticide) %>%
        summarize(average_weight = mean(avg_weight, na.rm = TRUE),
                  se = std.error(avg_weight, na.rm = TRUE))
kbs_bio <- ggplot(biomass_sum_k3, aes(x = state, y = average_weight, fill = state)) +
        facet_grid(.~insecticide, labeller = as_labeller(insect_labels)) +
        geom_bar(position = "identity", stat = "identity", col = "black") +
        geom_errorbar(aes(ymin = average_weight - se, ymax = average_weight + se), width = 0.2,
                      position = "identity") +
        labs(title="KBS", y=NULL, x=NULL) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_x_discrete(labels=c("ambient" = NULL, "warmed" = NULL)) +
        theme_bw(14) +
        theme(plot.title = element_text(size=20),
              axis.text.y = element_text(size=17))
# plot level UMBS
biomass_sum_u2 <- umbs_biomass_live %>%
        group_by(plot, state, insecticide) %>%
        summarize(avg_weight = sum(weight_g, na.rm = TRUE))
biomass_sum_u3 <- biomass_sum_u2 %>%
        group_by(state, insecticide) %>%
        summarize(average_weight = mean(avg_weight, na.rm = TRUE),
                  se = std.error(avg_weight, na.rm = TRUE))
umbs_bio <- ggplot(biomass_sum_u3, aes(x = state, y = average_weight, fill = state)) +
        facet_grid(.~insecticide, labeller = as_labeller(insect_labels)) +
        geom_bar(position = "identity", stat = "identity", col = "black") +
        geom_errorbar(aes(ymin = average_weight - se, ymax = average_weight + se), width = 0.2,
                      position = "identity") +
        labs(title="UMBS", y=NULL, x=NULL)+
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
                          labels=c("ambient"="Ambient","warmed"="Warmed")) +
        theme_bw(14) +
        theme(plot.title = element_text(size = 20),
              axis.text.x = element_text(size=17),
              axis.text.y = element_text(size=17)) +
        scale_x_discrete(labels=c("ambient"="Ambient","warmed"="Warmed"))

biomass_comb <- ggpubr::ggarrange(kbs_bio, umbs_bio,
                                     nrow = 2, common.legend = T, legend="none")
png("biomass_plots_L2_barplot.png", units="in", width=8, height=8, res=300)
annotate_figure(biomass_comb,
                left = text_grob("Plant Biomass (g/0.2m^2)", color = "black", rot = 90, size=18),
                bottom = text_grob("Treatment", color = "black", size=18))
dev.off()


### Overall averages btwn treatments - dot plot
# plot level KBS
kbs_bio_dot <- ggplot(biomass_sum_k3, aes(x = state, y = average_weight, fill = insecticide)) +
        geom_pointrange(aes(ymin=average_weight-se, ymax=average_weight+se), pch=21,size=1,position=position_dodge(0.2)) +
        #scale_shape_manual(name="Treatment",
                       #                   values = c(1, 19),
                       #                   labels=c("Herbivory","Reduced Herbivory")) +
                       scale_fill_manual(name="Treatment",
                                          values = c("#FFB451", "#0b0055"),
                                          labels=c("Herbivory","Reduced Herbivory")) +
        labs(title="KBS", y=NULL, x=NULL) +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        ylim(90,200) +
        theme_bw(14) +
        theme(plot.title = element_text(size=17),
              axis.text.x = element_text(size=15),
              axis.text.y = element_text(size=15),
              legend.text = element_text(size=15),
              legend.title = element_text(size=17))
# plot level UMBS
umbs_bio_dot <- ggplot(biomass_sum_u3, aes(x = state, y = average_weight, fill = insecticide)) +
        geom_pointrange(aes(ymin=average_weight-se, ymax=average_weight+se), pch=21,size=1,position=position_dodge(0.2)) +
        #scale_shape_manual(name="Treatment",
                       #                   values = c(1, 19),
                       #                   labels=c("Herbivory","Reduced Herbivory")) +
                       scale_fill_manual(name="Treatment",
                                          values = c("#FFB451", "#0b0055"),
                                          labels=c("Herbivory","Reduced Herbivory")) +
        labs(title="UMBS", y=NULL, x=NULL) +
        ylim(30,65) +
        theme_bw(14) +
        theme(plot.title = element_text(size = 17),
              axis.text.x = element_text(size=15),
              axis.text.y = element_text(size=15),
              legend.text = element_text(size=15),
              legend.title = element_text(size=17)) +
        scale_x_discrete(labels=c("ambient"="Ambient","warmed"="Warmed"))

biomass_comb_dot <- ggpubr::ggarrange(kbs_bio_dot, umbs_bio_dot,
                                     ncol = 2, common.legend = T, legend="right")
png("biomass_plots_dots_L2.png", units="in", width=8, height=4.5, res=300)
annotate_figure(biomass_comb_dot,
                left = text_grob(bquote("Plant Biomass " ('g/0.20m'^2)), color = "black", rot = 90, size=18))
dev.off()


### Overall averages btwn treatments - boxplot
# species level KBS
ggplot(kbs_biomass_live, aes(x = state, y = weight_g, fill=state)) +
        geom_boxplot(outlier.shape=NA, alpha=0.7) +
        geom_jitter(aes(alpha=0.6, color=state, fill=state), shape=16, size=2) +
        scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        labs(title="KBS - species level")+
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        theme_classic()
# plot level KBS
ggplot(biomass_sum_k2, aes(x = state, y = avg_weight, fill=state)) +
        geom_boxplot(outlier.shape=NA, alpha=0.7) +
        geom_jitter(aes(alpha=0.6, color=state, fill=state), shape=16, size=2) +
        scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        labs(title="KBS - plot level")+
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        theme_classic()
# species level UMBS
ggplot(umbs_biomass_live, aes(x = state, y = weight_g, fill=state)) +
        geom_boxplot(outlier.shape=NA, alpha=0.7) +
        geom_jitter(aes(alpha=0.6, color=state, fill=state), shape=16, size=2) +
        scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        labs(title="UMBS")+
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        theme_classic()
# plot level UMBS
ggplot(biomass_sum_u2, aes(x = state, y = avg_weight, fill=state)) +
        geom_boxplot(outlier.shape=NA, alpha=0.7) +
        geom_jitter(aes(alpha=0.6, color=state, fill=state), shape=16, size=2) +
        scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        labs(title="UMBS")+
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        theme_classic()


### Line plot of species responses to warming
mod11_k <- lm(log(weight_g) ~ state * species, kbs_biomass_live2)
emmip(mod11_k, species~state) +
        labs(title="KBS")
mod11_u <- lm(log(weight_g) ~ state * species, umbs_biomass_live2)
emmip(mod11_u, species~state)+
        labs(title="UMBS")

### Differences between warmed and ambient at a species level
biomass_spp_k <- kbs_biomass_live2 %>%
        group_by(species, state, insecticide) %>%
        summarize(avg_weight = mean(weight_g, na.rm = TRUE),
                  se = std.error(weight_g, na.rm = TRUE))
kbs_spp <- ggplot(biomass_spp_k, aes(x = state, y = avg_weight, fill = insecticide)) +
        facet_wrap(~species, ncol=4,scales="free_y") +
        geom_pointrange(aes(ymin=avg_weight-se, ymax=avg_weight+se), pch=21,size=0.6,position=position_dodge(0.4)) +
        #geom_bar(position = "dodge", stat = "identity", col = "black") +
        #geom_errorbar(aes(ymin = avg_weight - se, ymax = avg_weight + se), width = 0.2,
        #              position = position_dodge(0.9)) +
        labs(title="KBS",x=NULL,y=NULL) +
        scale_fill_manual(name="Treatment",
                                         values = c("#FFB451", "#0b0055"),
                                         labels=c("Herbivory","Reduced Herbivory")) +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
        theme_bw(14) +
        theme(axis.title = element_text(size=14))

biomass_spp_u <- umbs_biomass_live2 %>%
        group_by(species, state, insecticide) %>%
        summarize(avg_weight = mean(weight_g, na.rm = TRUE),
                  se = std.error(weight_g, na.rm = TRUE))
umbs_spp <- ggplot(biomass_spp_u, aes(x = state, y = avg_weight, fill = insecticide)) +
        facet_wrap(~species, ncol=4,scales="free_y") +
        geom_pointrange(aes(ymin=avg_weight-se, ymax=avg_weight+se), pch=21,size=0.6,position=position_dodge(0.4)) +
        #geom_bar(position = "dodge", stat = "identity", col = "black") +
        #geom_errorbar(aes(ymin = avg_weight - se, ymax = avg_weight + se), width = 0.2,
        #              position = position_dodge(0.9)) +
        labs(title="UMBS",x=NULL,y=NULL) +
        scale_fill_manual(name="Treatment",
                                         values = c("#FFB451", "#0b0055"),
                                         labels=c("Herbivory","Reduced Herbivory")) +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
        theme_bw(14)+
        theme(axis.title = element_text(size=14))

biomass_spp_comb <- ggpubr::ggarrange(kbs_spp, umbs_spp,
                                     ncol = 2, common.legend = T, legend="right")
png("biomass_plots_spp_L2_barplot.png", units="in", width=13, height=6, res=300)
annotate_figure(biomass_spp_comb,
                left = text_grob("Plant Biomass (g)", size=14, color = "black", rot = 90),
                bottom = text_grob("Treatment", size=14, color = "black"))
dev.off()

# Density histogram
ggplot(kbs_biomass_live, aes(weight_g, fill = state, colour = state)) +
        geom_density(alpha = 0.2) +
        labs(title="KBS - all species") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_colour_manual(values = c("#a6bddb", "#fb6a4a")) +
        theme_minimal()
ggplot(biomass_sum_k2, aes(avg_weight, fill = state, colour = state)) +
        geom_density(alpha = 0.2) +
        labs(title="KBS - plot level") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_colour_manual(values = c("#a6bddb", "#fb6a4a")) +
        theme_minimal()
ggplot(umbs_biomass_live, aes(weight_g, fill = state, colour = state)) +
        geom_density(alpha = 0.2) +
        labs(title="UMBS - all species") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_colour_manual(values = c("#a6bddb", "#fb6a4a")) + 
        theme_minimal()
ggplot(biomass_sum_u2, aes(avg_weight, fill = state, colour = state)) +
        geom_density(alpha = 0.2) +
        labs(title="UMBS - plot level") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_colour_manual(values = c("#a6bddb", "#fb6a4a")) +
        theme_minimal()

## Regression between cover and biomass
# making a dataframe for regression between cover and biomass - removing uninformative species first
kbs_biomass_reg <- kbs_biomass_21[!grepl("Litter", kbs_biomass_21$species),]
kbs_biomass_reg <- kbs_biomass_reg[!grepl("Total Live", kbs_biomass_reg$species),]
kbs_biomass_reg <- kbs_biomass_reg[!grepl("Unknown", kbs_biomass_reg$species),]
kbs_biomass_reg <- kbs_biomass_reg[!grepl("Unsorted", kbs_biomass_reg$species),]
umbs_biomass_reg <- umbs_biomass_21[!grepl("Bare_Ground", umbs_biomass_21$species),]
umbs_biomass_reg <- umbs_biomass_reg[!grepl("Groundhog", umbs_biomass_reg$species),]
umbs_biomass_reg <- umbs_biomass_reg[!grepl("Litter", umbs_biomass_reg$species),]
umbs_biomass_reg <- umbs_biomass_reg[!grepl("Standing_Dead", umbs_biomass_reg$species),]
umbs_biomass_reg <- umbs_biomass_reg[!grepl("Surface_Litter", umbs_biomass_reg$species),]

# setting NA to 0 for cover or biomass for the regression
kbs_biomass_reg$cover[is.na(kbs_biomass_reg$cover)] <- 0
kbs_biomass_reg$weight_g[is.na(kbs_biomass_reg$weight_g)] <- 0
umbs_biomass_reg$cover[is.na(umbs_biomass_reg$cover)] <- 0
umbs_biomass_reg$weight_g[is.na(umbs_biomass_reg$weight_g)] <- 0

# fixing values listed as <1 for umbs
umbs_biomass_reg[umbs_biomass_reg=="<1"] <- 0
# making cover column numeric for umbs
umbs_biomass_reg$cover <- as.numeric(umbs_biomass_reg$cover)

# regression #
cor.test(kbs_biomass_reg$cover, kbs_biomass_reg$weight_g, method="pearson")
lm1_k <- lm(cover ~ weight_g, data = kbs_biomass_reg)
plot(cover ~ weight_g, data = kbs_biomass_reg)
abline(lm1_k)

cor.test(umbs_biomass_reg$cover, umbs_biomass_reg$weight_g, method="pearson")
lm1_u <- lm(cover ~ weight_g, data = umbs_biomass_reg)
plot(cover ~ weight_g, data = umbs_biomass_reg)
abline(lm1_u)

```