---
title: "warmXtrophic Project: Flowering First Date of Flower Analyses"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

Load in packages & data
```{r, message = F}
rm(list=ls()) # clear all existing data

#Load packages
library(tidyverse)
library(ggplot2)
library(lme4)
library(lmerTest)
library(emmeans)
library(vegan)
library(car)
library(rstatix)
library(scales)
library(fitdistrplus)
library(moments)# for calculating skewness of data
library(ggpubr)
library(jtools) # summ() function
library(predictmeans)
library(olsrr)
library(car)
library(fitdistrplus)
library(ggpubr)
library(interactions)
library(sjPlot)
library(effects)
library(glmmTMB)
library(GGally) # ggpairs() function
library(bbmle) # AICtab() function

# Set working directory
Sys.getenv("L1DIR")
L0_dir <- Sys.getenv("L0DIR")
L1_dir <- Sys.getenv("L1DIR")
L2_dir <- Sys.getenv("L2DIR")

# Read in data
flwr_plot <- read.csv(file.path(L2_dir, "phenology/final_flwr_plot_L2.csv")) # plot level data
flwr_plot$year_factor <- as.factor(flwr_plot$year_factor)

# species level first flower
# note: the species data frame is only used to demonstrate that first flwr differs between species (for the supplement)
flwr_spp <- read.csv(file.path(L2_dir, "phenology/final_flwr_species_L2.csv")) 
flwr_spp$julian_min <- as.numeric(as.integer(flwr_spp$julian_min))

```

```{r}
# delete 2021 data from dataframe - doesn't make sense to have bc we can't get min flower/sd, median flower, or 
# flower duration from 2021 UMBS since data was not collected at the same frequency as previous years
#flwr_plot <- flwr_plot[-which(flwr_plot$year == "2021" & flwr_plot$site == "umbs"),]
flwr_plot <- flwr_plot[-which(flwr_plot$year == "2015" & flwr_plot$site == "kbs"),]
flwr_spp <- flwr_spp[-which(flwr_spp$year == "2015" & flwr_spp$site == "kbs"),]

umbs_plot <- subset(flwr_plot, site == "umbs") # pull out umbs only data at plot level
kbs_plot <- subset(flwr_plot, site == "kbs") # pull out kbs only data at plot level

# species specific dataframes for kbs and umbs
flwr_kbs_spp <- subset(flwr_spp, site == "kbs")
flwr_umbs_spp <- subset(flwr_spp, site == "umbs")
```

KBS Plot Level
```{r}
### KBS ###
hist(kbs_plot$julian_min)
qqnorm(kbs_plot$julian_min)
shapiro.test(kbs_plot$julian_min) # pvalue is < 0.05 so we reject the null hypothesis that the data is normal (aka not normally distributed) but it looks normal enough

# Exploring distributions for these right-skewed data:
descdist(kbs_plot$julian_min, discrete = FALSE)

# Gamma distribution 
fit.gamma <- fitdist(kbs_plot$julian_min, "gamma")
plot(fit.gamma)

# Weibull distribution
fit.weibull  <- fitdist(kbs_plot$julian_min, "weibull")
plot(fit.weibull)

# Lognormal distribution 
fit.ln <- fitdist(kbs_plot$julian_min, "lnorm")
plot(fit.ln)

par(mfrow=c(2,2))
plot.legend <- c("Gamma", "Weibull", "Log Normal")
denscomp(list(fit.gamma, fit.weibull, fit.ln), legendtext = plot.legend)
cdfcomp (list(fit.gamma, fit.weibull, fit.ln), legendtext = plot.legend)
qqcomp  (list(fit.gamma, fit.weibull, fit.ln), legendtext = plot.legend)
ppcomp  (list(fit.gamma, fit.weibull, fit.ln), legendtext = plot.legend)
dev.off()

# Goodness of fit comparisons across fits (can't include the log normal bc it becomes diff response values)
gofstat(list(fit.gamma, fit.weibull, fit.ln), fitnames = c("Gamma", "Weibull", "Log Normal"))
# log normal best fit but data looks pretty normal so sticking with that
```

Leverage plots and detecting Outliers
```{r}
# Plot level data
# KBS State-only model
fit_plot_state_kbs <- lm(log(julian_min) ~ state, data = kbs_plot)
outlierTest(fit_plot_state_kbs) # line 168 outlier
qqPlot(fit_plot_state_kbs, main="QQ Plot") 
hist(fit_plot_state_kbs$residuals)
leveragePlots(fit_plot_state_kbs)
ols_test_normality(fit_plot_state_kbs) # looks ok besides Kolmogorov-Smirnov test

# KBS State and year model
fit_plot_stateyear_kbs <- lm(log(julian_min) ~ state + year_factor, data = kbs_plot)
outlierTest(fit_plot_stateyear_kbs) # outliers - 142, 155, 220, 116, 207, 272
qqPlot(fit_plot_stateyear_kbs, main="QQ Plot") 
hist(fit_plot_stateyear_kbs$residuals)
leveragePlots(fit_plot_stateyear_kbs)
ols_test_normality(fit_plot_stateyear_kbs) # a couple tests say not normal 

# Interaction plot (ignore for now the repeated measures with species); see: https://cran.r-project.org/web/packages/interactions/vignettes/interactions.html and: https://interactions.jacob-long.com/

fit3 <- lm(julian_min ~ state * year, data = kbs_plot)
interact_plot(fit3, pred = year, modx = state) 

# remove outlier, line 168
kbs_plot_nooutlier <- kbs_plot[!rownames(kbs_plot) == '168', ]
descdist(kbs_plot_nooutlier$julian_min, discrete = FALSE)
# KBS State-only model
fit_plot_state_kbs <- lm(julian_min ~ state, data = kbs_plot_nooutlier)
outlierTest(fit_plot_state_kbs) # no outliers
qqPlot(fit_plot_state_kbs, main="QQ Plot") 
hist(fit_plot_state_kbs$residuals)
leveragePlots(fit_plot_state_kbs)
ols_test_normality(fit_plot_state_kbs)
```

Mixed Effects Model
```{r}
# KBS PLOT LEVEL - Looking at FIRST date of flowering
mod1 <- lmer(julian_min ~ state*insecticide*year_factor + (1|plot), kbs_plot_nooutlier, REML = FALSE)

# Check Assumptions:
# (1) Linearity: if covariates are not categorical (year isn't)
# (2) Homogeneity: Need to Check by plotting residuals vs predicted values.
par(mfrow=c(1,2))
plot(mod1) # the ones in the data are making this look weird - idk this doesn't look great
# Check for homogeneity of variances (true if p>0.05). If the result is not significant, the assumption of equal variances (homoscedasticity) is met (no significant difference between the group variances).
# *****Levene’s Test - tests whether or not the variance among two or more groups is equal - If the p-value is less than our chosen significance level, we can reject the null hypothesis and conclude that we have enough evidence to state that the variance among the groups is not equal (which we want).

leveneTest(residuals(mod1) ~ kbs_plot_nooutlier$state)
# Assumption met
leveneTest(residuals(mod1) ~ kbs_plot_nooutlier$insecticide) 
# Assumption not met
leveneTest(residuals(mod1) ~ kbs_plot_nooutlier$plot)
# Assumption met

# (3) Normality of error term: need to check by histogram, QQplot of residuals, could do Kolmogorov-Smirnov test.
# Check for normal residuals
qqPlot(resid(mod1))
hist(residuals(mod1))
shapiro.test(resid(mod1)) # normally distributed resids bc p>0.05
outlierTest(mod1) # no outliers
```

# KBS Plot-level model - ALL YEARS
```{r}
#Our hypothesized model is  mod9p
mod_k_all <- lmer(log(julian_min) ~ state * insecticide * year_factor + (1|plot), kbs_plot_nooutlier, REML=FALSE)
summary(mod_k_all)
anova(mod_k_all)

# calculating effect size - accounting for log transformation
exp((5.146226) +  (0.005052)*0) # 171.782 
exp((5.146226) +  (0.005052)*1) # 172.652
# effect:
172.652 - 171.782 # effect of warming - warmed plots increased the date of first flower by 0.87 days

# comparisons
contrast.k <- contrast(emmeans(mod_k_all, ~state*year_factor), "pairwise", simple = "each", combine = F, adjust = "mvt")

result = as.data.frame(contrast.k)

result <- result %>%
mutate_if(is.numeric, round, digits=2)

# table
kable(result) %>% kableExtra::kable_styling()

# adding in our temp data into some models
# note: including state, year, and temp data into a model leads to rank deficiency
# so below, we test for date of first flower as a function of just temp to see how real temp data affects date of first flower
kbs_plot_amb <- kbs_plot %>%
        filter(state == "ambient")
modtest1 <- lmer(log(julian_min) ~ mean_temp + (1|plot), kbs_plot, REML=FALSE)
modtest2 <- lmer(log(julian_min) ~ GDD_cumulative + (1|plot), kbs_plot, REML=FALSE)

AICtab(modtest1, modtest2, weights=T)
# growing degree days model is better but we are going to use the mean temp for all models

anova(modtest1)
summary(modtest1)

r.squaredGLMM(modtest1)
# making a table
kable(anova(modtest1)) %>% kableExtra::kable_styling()
```

UMBS plot level
```{r}
### UMBS ###
hist(umbs_plot$julian_min)
qqnorm(umbs_plot$julian_min)
shapiro.test(umbs_plot$julian_min) # pvalue is > 0.05 so we fail to reject the null hypothesis that the data is normal (aka normally distributed!!)
```

Leverage plots and detecting Outliers
```{r}
# Plot level data
# UMBS State-only model
fit_plot_state_umbs <- lm(julian_min ~ state, data = umbs_plot)
outlierTest(fit_plot_state_umbs) # no outliers
qqPlot(fit_plot_state_umbs, main="QQ Plot") 
hist(fit_plot_state_umbs$residuals)
leveragePlots(fit_plot_state_umbs)
ols_test_normality(fit_plot_state_umbs) # looks ok besides Kolmogorov-Smirnov test

# UMBS State and year model
fit_plot_stateyear_umbs <- lm(julian_min ~ state + year_factor, data = umbs_plot)
outlierTest(fit_plot_stateyear_umbs) 
qqPlot(fit_plot_stateyear_umbs, main="QQ Plot") 
hist(fit_plot_stateyear_umbs$residuals)
leveragePlots(fit_plot_stateyear_umbs)
ols_test_normality(fit_plot_stateyear_umbs) # a couple tests say not normal 

# Interaction plot (ignore for now the repeated measures with species); see: https://cran.r-project.org/web/packages/interactions/vignettes/interactions.html and: https://interactions.jacob-long.com/

fit3 <- lm(julian_min ~ state * year, data = umbs_plot)
interact_plot(fit3, pred = year, modx = state) # this looks very strange to me
```

# UMBS Plot-level model - ALL YEARS
```{r}
#Our hypothesized model is  mod9p
mod_u_all <- lmer(julian_min ~ state * insecticide * year_factor + (1|plot), umbs_plot, REML=FALSE)
summary(mod_u_all)
anova(mod_u_all)

# making a table
kable(anova(mod_u_all), digits = 2) %>% kableExtra::kable_styling()

# adding in our temp data into some models
# note: including state, year, and temp data into a model leads to rank deficiency
# so below, we test for date of first flower as a function of just temp to see how real temp data affects date of first flower
umbs_plot_amb <- umbs_plot %>%
        filter(state == "ambient")
modtest1u <- lmer(julian_min ~ mean_temp + (1|plot), umbs_plot, REML=FALSE)
modtest2u <- lmer(julian_min ~ GDD_cumulative + (1|plot), umbs_plot, REML=FALSE)

AICtab(modtest1u,modtest2u, weights = T)

anova(modtest1u)
summary(modtest1u)

r.squaredGLMM(modtest1u)

# making a table
kable(anova(modtest1u)) %>% kableExtra::kable_styling()

```

Species models for supplement
```{r}
# KBS
# species model for supp
mod_spp_k <- lmer(julian_min ~ state * insecticide * as.factor(year_factor) + species + (1|plot), flwr_kbs_spp, REML=FALSE)
anova(mod_spp_k)
# making a table
kable(anova(mod_spp_k), digits = 2) %>% kableExtra::kable_styling()

# UMBS
# species model for supp
mod_spp_u <- lmer(julian_min ~ state * insecticide * as.factor(year_factor) + species + (1|plot), flwr_umbs_spp, REML=FALSE)
anova(mod_spp_u)
# making a table
kable(anova(mod_spp_u), digits = 2) %>% kableExtra::kable_styling()
```




KBS and UMBS models not used in manuscript
```{r}
#Our hypothesized model is  mod9p
mod9p <- lmer(log(julian_min) ~ state * insecticide + year_factor + (1|plot), kbs_plot, REML=FALSE)
summary(mod9p)
anova(mod9p)

# making a table
kable(anova(mod9p)) %>% kableExtra::kable_styling()

# calculating effect size - accounting for log transformation
exp((5.164064) +  (0.013017)*0) # 174.8737 
exp((5.164064) +  (0.013017)*1) # 177.1649
# effect:
177.1649 - 174.8737 # effect of warming - warmed plots increased the date of first flower by 2.2912 days
```

```{r}
#Our hypothesized model is  mod9p
mod9pu <- lmer(julian_min ~ state * insecticide + year_factor + (1|plot), umbs_plot, REML=FALSE)
summary(mod9pu)
anova(mod9pu)

# making a table
kable(anova(mod9pu)) %>% kableExtra::kable_styling()
```

```{r}
#KBS
mod1p <- lmer(log(julian_min) ~ state + (1|plot), kbs_plot, REML=FALSE)
mod2p <- lmer(log(julian_min) ~ insecticide + (1|plot), kbs_plot, REML=FALSE)
mod3p <- lmer(log(julian_min) ~ insecticide + state + (1|plot), kbs_plot, REML=FALSE)
mod4p <- lmer(log(julian_min) ~ insecticide * state + (1|plot), kbs_plot, REML=FALSE)
mod5p <- lmer(log(julian_min) ~ state + year_factor + (1|plot), kbs_plot, REML=FALSE)
mod6p <- lmer(log(julian_min) ~ state + year_factor + insecticide + (1|plot), kbs_plot, REML=FALSE)
mod7p <- lmer(log(julian_min) ~ state * year_factor + (1|plot), kbs_plot, REML=FALSE)
mod8p <- lmer(log(julian_min) ~ state * year_factor + insecticide + (1|plot), kbs_plot, REML=FALSE)
mod9p <- lmer(log(julian_min) ~ state * insecticide + year_factor + (1|plot), kbs_plot, REML=FALSE)
mod10p <- lmer(log(julian_min) ~ state + insecticide * year_factor + (1|plot), kbs_plot, REML=FALSE)
mod11p <- lmer(log(julian_min) ~ state * year_factor * insecticide + (1|plot), kbs_plot, REML=FALSE)
AICctab(mod1p, mod2p, mod3p, mod4p, mod5p, mod6p, mod7p, mod8p, mod9p, mod10p, mod11p, weights=T) # model 7p and 8p are the top models
anova(mod7p, mod8p) # go with 7p although they are nearly identical
AICctab(mod7p, mod8p, weights=T) # 7p
summ(mod7p)
anova(mod7p)
summary(mod7p)
emmeans(mod7p, list(pairwise ~ state*year_factor), adjust = "tukey")

kbs_plot$year_factor <- as.factor(kbs_plot$year_factor)
mod7p %>%
  emmeans(pairwise ~ state | year_factor) %>%
  pluck("contrasts")

#including herb reduction
anova(mod8p)
#including herb reduction as interactive term
anova(mod9p)

# comparisons
emmeans(mod9p, list(pairwise ~ state*insecticide), adjust = "tukey")
emmeans(mod9p, list(pairwise ~ state), adjust = "tukey")
mod9p.emm <- emmeans(mod9p, ~ state*insecticide)
contrast(mod9p.emm, "consec", simple = "each", combine = F, adjust = "mvt")
emmip(mod9p, insecticide~state)

#UMBS
mod1pu <- lmer(julian_min ~ state + (1|plot), umbs_plot, REML=FALSE)
mod2pu <- lmer(julian_min ~ insecticide + (1|plot), umbs_plot, REML=FALSE)
mod3pu <- lmer(julian_min ~ insecticide + state + (1|plot), umbs_plot, REML=FALSE)
mod4pu <- lmer(julian_min ~ insecticide * state + (1|plot), umbs_plot, REML=FALSE)
mod5pu <- lmer(julian_min ~ state + year_factor + (1|plot), umbs_plot, REML=FALSE)
mod6pu <- lmer(julian_min ~ state + year_factor + insecticide + (1|plot), umbs_plot, REML=FALSE)
mod7pu <- lmer(julian_min ~ state * year_factor + (1|plot), umbs_plot, REML=FALSE)
mod8pu <- lmer(julian_min ~ state * year_factor + insecticide + (1|plot), umbs_plot, REML=FALSE)
mod9pu <- lmer(julian_min ~ state * insecticide + year_factor + (1|plot), umbs_plot, REML=FALSE)
mod10pu <- lmer(julian_min ~ state + insecticide * year_factor + (1|plot), umbs_plot, REML=FALSE)
mod11pu <- lmer(julian_min ~ state * year_factor * insecticide + (1|plot), umbs_plot, REML=FALSE)
AICctab(mod1pu, mod2pu, mod3pu, mod4pu, mod5pu, mod6pu, mod7pu, mod8pu, mod9pu, mod10pu, mod11pu, weights=T) # model 10p and 6p are the top models
anova(mod10pu, mod6pu) # go with 10p
AICctab(mod10pu, mod6pu, weights=T) #10p
summ(mod10pu)
summary(mod10pu)
anova(mod10pu)
emmeans(mod10pu, list(pairwise ~ state + year_factor), adjust = "tukey")
emmeans(mod10pu, list(pairwise ~ insecticide*year_factor), adjust = "tukey")
emmeans(mod10pu, list(pairwise ~ year_factor), adjust = "tukey")

# comparisons
emmeans(mod9pu, list(pairwise ~ state*insecticide), adjust = "tukey")
mod9pu.emm <- emmeans(mod9pu, ~ state*insecticide)
contrast(mod9pu.emm, "consec", simple = "each", combine = F, adjust = "mvt")
emmip(mod9pu, insecticide~state)

```

