---
title: "Height Analysis"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(lmerTest)
library(car)
library(bbmle)
library(sjPlot)
library(emmeans)
library(stats)
library(knitr)
library(fitdistrplus)

# Get data
Sys.getenv("L1DIR")
L1_dir<-Sys.getenv("L1DIR")
list.files(L1_dir)
kbs_height <- read.csv(file.path(L1_dir, "height/kbs_height_L1.csv"))
umbs_height <- read.csv(file.path(L1_dir, "height/umbs_height_L1.csv"))

# remove NAs in the height_cm column
kbs_height <- kbs_height %>%  filter(!is.na(height_cm))
umbs_height <- umbs_height %>%  filter(!is.na(height_cm))
```

# KBS
```{r}
descdist(kbs_height$height_cm, discrete = FALSE)
# Shapiro-Wilk test for normality
shapiro.test(kbs_height$height_cm) # almost normal
# Visualization
hist(kbs_height$height_cm, main = "Histogram of Height")
qqnorm(kbs_height$height_cm)
qqline(kbs_height$height_cm, col = "blue")

m1 <- lmer(height_cm ~ state + (1|plot), data = kbs_height)

# Check Assumptions:
# (1) Linearity: if covariates are not categorical
# (2) Homogeneity: Need to Check by plotting residuals vs predicted values.
plot(m1, main = "Height")
# Homogeneity of variance looks a bit off (increasing variance in resids does increase with fitted values)
# Check for homogeneity of variances (true if p>0.05). If the result is not significant, the assumption of equal variances (homoscedasticity) is met (no significant difference between the group variances).
leveneTest(residuals(m1) ~ kbs_height$state) # met
# (3) Normality of error term: need to check by histogram, QQplot of residuals, could do Kolmogorov-Smirnov test.
# Check for normal residuals
qqPlot(resid(m1), main = "Height")
hist(residuals(m1), main = "Height")
shapiro.test(resid(m1)) # normal
outlierTest(m1) # checking for outliers - none

anova(m1)
#Type III Analysis of Variance Table with Satterthwaite's method
#      Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
#state  18892   18892     1 20.991  29.059 2.401e-05 ***
summary(m1)

# make model table for supp
kable(anova(m1), digits = 3) %>% kableExtra::kable_styling()

# Pairwise comparisons
em1 <- contrast(emmeans(m1, ~state), "pairwise", simple = "each", combine = F, adjust = "mvt")
em1
#contrast         estimate  SE df t.ratio p.value
#ambient - warmed    -37.2 6.9 21  -5.389  <.0001

# Extract estimates
ambient <- fixef(m1)[["(Intercept)"]] # Ambient treatment mean
warmed_effect <- fixef(m1)[["statewarmed"]] # Effect of warmed treatment
# Calculate warmed mean
warmed <- ambient + warmed_effect
# Percentage increase
percent_increase <- (warmed_effect / ambient) * 100
percent_increase
```

# UMBS
```{r}
descdist(umbs_height$height_cm, discrete = FALSE)
# Shapiro-Wilk test for normality
shapiro.test(umbs_height$height_cm) # almost normal
# Visualization
hist(umbs_height$height_cm, main = "Histogram of Height")
qqnorm(umbs_height$height_cm)
qqline(umbs_height$height_cm, col = "blue")

m2 <- lmer(height_cm ~ state + (1|plot), data = umbs_height)

# Check Assumptions:
# (1) Linearity: if covariates are not categorical
# (2) Homogeneity: Need to Check by plotting residuals vs predicted values.
plot(m2, main = "Height")
# Homogeneity of variance looks a bit off (increasing variance in resids does increase with fitted values)
# Check for homogeneity of variances (true if p>0.05). If the result is not significant, the assumption of equal variances (homoscedasticity) is met (no significant difference between the group variances).
leveneTest(residuals(m2) ~ umbs_height$state) # not met
# (3) Normality of error term: need to check by histogram, QQplot of residuals, could do Kolmogorov-Smirnov test.
# Check for normal residuals
qqPlot(resid(m2), main = "Height")
hist(residuals(m2), main = "Height")
shapiro.test(resid(m2)) # normal
outlierTest(m2) # checking for outliers - none

anova(m2)
#Type III Analysis of Variance Table with Satterthwaite's method
#      Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
#state   3578    3578     1 18.615  21.555 0.0001864 ***
summary(m2)

# make model table for supp
kable(anova(m2), digits = 3) %>% kableExtra::kable_styling()

# Pairwise comparisons
em2 <- contrast(emmeans(m2, ~state), "pairwise", simple = "each", combine = F, adjust = "mvt")
em2
#contrast         estimate   SE   df t.ratio p.value
#ambient - warmed    -21.4 4.61 19.9  -4.635  0.0002

# Extract estimates
ambient <- fixef(m2)[["(Intercept)"]] # Ambient treatment mean
warmed_effect <- fixef(m2)[["statewarmed"]] # Effect of warmed treatment
# Calculate warmed mean
warmed <- ambient + warmed_effect
# Percentage increase
percent_increase <- (warmed_effect / ambient) * 100
percent_increase
```

