---
title: "warmXtrophic Project: Herbivory Analyses"
author: "Kara Dobson"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in and prepare data for analyses  
```{r, message = F}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(lmerTest)
library(olsrr)
library(predictmeans)
library(car)
library(fitdistrplus)
library(MASS)
library(pscl)
library(lmtest)
library(emmeans)
library(bbmle)

# Get data
#Sys.getenv("L1DIR")
L1_dir<-Sys.getenv("L1DIR")
#list.files(L1_dir)
herb <- read.csv(file.path(L1_dir, "herbivory/final_herbivory_L1.csv"))

# changing scale of years
herb$year1<-herb$year
herb$year[herb$year == 2015] <- 1
herb$year[herb$year == 2016] <- 2
herb$year[herb$year == 2017] <- 3
herb$year[herb$year == 2018] <- 4
herb$year[herb$year == 2019] <- 5
herb$year[herb$year == 2020] <- 6

# Remove NAs
herb <- herb[complete.cases(herb),]

# create dataframes for kbs and umbs only for plots with no insecticide
herb_kbs <- subset(herb, site == "kbs" & insecticide == "insects")
herb_umbs <- subset(herb, site == "umbs" & insecticide == "insects")

# only keep species that were recorded in both warmed and ambient plots
herb_kbs <- herb_kbs %>%
        group_by(species) %>% 
        filter(all(c('warmed', 'ambient') %in% state))
herb_umbs <- herb_umbs %>%
        group_by(species) %>% 
        filter(all(c('warmed', 'ambient') %in% state))

# checking to see if any species/state combos are all zeros
with(herb_kbs,table(species,state,p_eaten==0)) 
with(herb_umbs,table(species,state,p_eaten==0))

# number of observation per species/state combo (to find rare species)
herb_kbs %>% count(state, species)
herb_umbs %>% count(state, species)

# removing rare species from KBS
herb_kbs <- herb_kbs[!grepl("Hype",herb_kbs$species),]
herb_kbs %>% count(state, species)

# How much of the data is zeros?
100*sum(herb_kbs$p_eaten == 0)/nrow(herb_kbs) #68% - thats a lot! probably have to use a zero-inflated model,
# but I'll still check for normality & try some transformations below
100*sum(herb_umbs$p_eaten == 0)/nrow(herb_umbs) #61%
```

# KBS Data Exploration
```{r, message = F}
descdist(herb_kbs$p_eaten, discrete = FALSE)
# normal distribution?
hist(herb_kbs$p_eaten)
qqnorm(herb_kbs$p_eaten)
shapiro.test(herb_kbs$p_eaten)
fit <- lm(p_eaten~state, data = herb_kbs)
qqPlot(fit)

# looking at each treatment separately
hist(herb_kbs$p_eaten[herb_kbs$state == "ambient"])
hist(herb_kbs$p_eaten[herb_kbs$state == "warmed"])

# gamma distribution? - error message "the function mle failed to estimate the parameters"
#fit.gamma <- fitdist(herb_kbs$p_eaten, "gamma")
#plot(fit.gamma)

# lognormal distribution? - error message "values must be positive to fit a lognormal"
#fit.ln <- fitdist(herb_kbs$p_eaten, "lnorm")
#plot(fit.ln)

# log transform
herb_kbs$p_log <- log(herb_kbs$p_eaten+1)
hist(herb_kbs$p_log)
qqnorm(herb_kbs$p_log)
shapiro.test(herb_kbs$p_log) # NAs - data contains 0s

# mean centering p_eaten
herb_kbs$p_scaled <- herb_kbs$p_log - mean(herb_kbs$p_log)
hist(herb_kbs$p_scaled)
hist(herb_kbs$p_scaled[herb_kbs$state == "ambient"])
hist(herb_kbs$p_scaled[herb_kbs$state == "warmed"])
qqnorm(herb_kbs$p_scaled)
shapiro.test(herb_kbs$p_scaled)

# square root?
herb_kbs$p_sqrt <- sqrt(herb_kbs$p_eaten)
hist(herb_kbs$p_sqrt)
qqnorm(herb_kbs$p_sqrt)
shapiro.test(herb_kbs$p_sqrt)
```

## Transformations are a no-go
## Going to try a zero-inflated model due to the excess number of zeros in the data
```{r}
# mean and var of non-zero counts
herb_kbs %>%
  dplyr::filter(p_eaten != "0") %>%
  dplyr::summarize(mean_eaten = mean(p_eaten, na.rm=T), var_eaten = var(p_eaten, na.rm=T))
# variance is also > mean, so can't be poisson
# I'll try zero-inflated negative binomial due to an excess of zeros

# zero-inflated negative binomial
# state as a fixed effect
k.m1 <- zeroinfl(p_eaten ~ state,
               dist = 'negbin',
               data = herb_kbs)
summary(k.m1)

# state and year as fixed effects
k.m2 <- zeroinfl(p_eaten ~ state + as.factor(year),
               dist = 'negbin',
               data = herb_kbs)
summary(k.m2)
lrtest(k.m1, k.m2) # model 2

# state and growth habit as fixed effects
herb_kbs <- within(herb_kbs, growth_habit <- relevel(factor(growth_habit), ref = "Forb")) # releveling so forb is the reference
k.m3 <- zeroinfl(p_eaten ~ state + growth_habit,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m3)
lrtest(k.m2, k.m3) # model 2

# state, growth habit, and year as fixed effects
k.m4 <- zeroinfl(p_eaten ~ state + growth_habit + as.factor(year),
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m4)
lrtest(k.m2, k.m4) # model 4

# interaction between state and growth habit as fixed effects
k.m5 <- zeroinfl(p_eaten ~ state * growth_habit,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m5)
lrtest(k.m4, k.m5) # model 4

# interaction between state and growth habit as fixed effects, plus year
k.m6 <- zeroinfl(p_eaten ~ state * growth_habit + as.factor(year),
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m6)
lrtest(k.m4, k.m6) # virtually the same, keeping model 4 because its simpler
# calculating effect size of graminoids vs forb herbivory - accounting for log link
exp(0.470803 + 1.234010*0) # 1.60128
exp(0.470803 + 1.234010*1) # 5.500357
# effect of herbivory:
5.500357 - 1.60128 # 3.899077

# interaction between state, growth habit, and year (year as a factor wouldn't work - non-finite value)
k.m7 <- zeroinfl(p_eaten ~ state * growth_habit * year,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m7)
lrtest(k.m4, k.m7) # model 4

# state and origin as fixed effects
herb_kbs <- within(herb_kbs, origin <- relevel(factor(origin), ref = "Native")) # releveling so native is the reference
k.m8 <- zeroinfl(p_eaten ~ state + origin,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m8)
lrtest(k.m4, k.m8) # model 4

# state, origin, and year as fixed effects
k.m9 <- zeroinfl(p_eaten ~ state + origin + as.factor(year),
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m9)
lrtest(k.m4, k.m9) # model 4

# interaction between state and origin as fixed effects
k.m10 <- zeroinfl(p_eaten ~ state * origin,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m10)
lrtest(k.m4, k.m10) # model 4

# interaction between state and origin as fixed effects, plus year
k.m11 <- zeroinfl(p_eaten ~ state * origin + as.factor(year),
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m11)
lrtest(k.m4, k.m11) # model 4
exp(0.43056 + 0.37613*0) # 1.538119
exp(0.43056 + 0.37613*1) # 2.24048
# effect of herbivory:
2.24048 - 1.538119 # 0.702361

# interaction between state, origin, and year
k.m12 <- zeroinfl(p_eaten ~ state * origin * year,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m12)
lrtest(k.m4,k.m12) # model 4

# just origin - testing to see w/o state
k.m12.2 <- zeroinfl(p_eaten ~ origin,
                   dist = 'negbin',
                   data = herb_kbs)
summary(k.m12.2)

# state and species as fixed effects
k.m13 <- zeroinfl(p_eaten ~ state + species,
                     dist = 'negbin',
                     data = herb_kbs)
summary(k.m13)
lrtest(k.m4, k.m13) # model 4

# state. species and year as fixed effects
k.m14 <- zeroinfl(p_eaten ~ state + species + as.factor(year),
                     dist = 'negbin',
                     data = herb_kbs)
summary(k.m14)
lrtest(k.m4, k.m14) # model 14
# calculating effect size - accounting for log link
exp(0.27490 + -0.22879*0) # 1.316399
exp(0.27490 + -0.22879*1) # 1.04719
# effect of herbivory:
1.04719 - 1.316399 # -0.269209

# interaction between state and species as fixed effects, plus year
k.m15 <- zeroinfl(p_eaten ~ state * species + as.factor(year),
                     dist = 'negbin',
                     data = herb_kbs)
summary(k.m15)
lrtest(k.m14, k.m15) # model 15 slightly better, going with 14 because its simpler

# checking models again
lrtest(k.m2, k.m4, k.m9, k.m14) # model 14 best - with species
res.k <- AIC(k.m1, k.m2, k.m3, k.m4, k.m5, k.m6, k.m7, k.m8, k.m9, k.m10, k.m11,k.m12,k.m13,k.m14,k.m15)

## interaction between state, species, and year - doesn't run
#m8 <- zeroinfl(p_eaten ~ state * species * as.factor(year),
#                     dist = 'negbin',
#                     data = herb_kbs)
#summary(m8)

# check dispersion
E <- resid(k.m14, type = "pearson")
N  <- nrow(herb_kbs)
p  <- length(coef(k.m14)) + 1 # '+1' is due to theta
sum(E^2) / (N - p) # a little overdispersed - is that okay?

# pairwise comparisons
emmeans(k.m14, ~ state + species + as.factor(year))
```

# UMBS - Data Exploration
```{r, messagae = F}
descdist(herb_umbs$p_eaten, discrete = FALSE)
# normal distribution?
hist(herb_umbs$p_eaten)
qqnorm(herb_umbs$p_eaten)
shapiro.test(herb_umbs$p_eaten)
fit <- lm(p_eaten~state, data = herb_umbs)
qqPlot(fit)

# looking at each treatment separately
hist(herb_umbs$p_eaten[herb_umbs$state == "ambient"])
hist(herb_umbs$p_eaten[herb_umbs$state == "warmed"])

# gamma distribution? - error message "the function mle failed to estimate the parameters"
#fit.gamma <- fitdist(herb_umbs$p_eaten, "gamma")
#plot(fit.gamma)

# lognormal distribution? - error message "values must be positive to fit a lognormal"
#fit.ln <- fitdist(herb_umbs$p_eaten, "lnorm")
#plot(fit.ln)

# log transform
herb_umbs$p_log <- log(herb_umbs$p_eaten+1)
hist(herb_umbs$p_log)
qqnorm(herb_umbs$p_log)
shapiro.test(herb_umbs$p_log) # NAs - data contains 0s

# mean centering p_eaten
herb_umbs$p_scaled <- herb_umbs$p_log - mean(herb_umbs$p_log)
hist(herb_umbs$p_scaled)
hist(herb_umbs$p_scaled[herb_umbs$state == "ambient"])
hist(herb_umbs$p_scaled[herb_umbs$state == "warmed"])
qqnorm(herb_umbs$p_scaled)
shapiro.test(herb_umbs$p_scaled)

# square root?
herb_umbs$p_sqrt <- sqrt(herb_umbs$p_eaten)
hist(herb_umbs$p_sqrt)
qqnorm(herb_umbs$p_sqrt)
shapiro.test(herb_umbs$p_sqrt)
```

## Transformations are a no-go
## Going to try a zero-inflated model due to the excess number of zeros in the data
```{r}
# mean and var of non-zero counts
herb_umbs %>%
        dplyr::filter(p_eaten != "0") %>%
        dplyr::summarize(mean_eaten = mean(p_eaten, na.rm=T), var_eaten = var(p_eaten, na.rm=T))
# variance is also > mean, so can't be poisson
# I'll try zero-inflated negative binomial due to an excess of zeros

# zero-inflated negative binomial
# state as a fixed effect
u.m1 <- zeroinfl(p_eaten ~ state,
               dist = 'negbin',
               data = herb_umbs)
summary(u.m1)

# state and year as fixed effects
u.m2 <- zeroinfl(p_eaten ~ state + as.factor(year),
               dist = 'negbin',
               data = herb_umbs)
summary(u.m2)
lrtest(u.m1, u.m2) # model 2

# state and growth habit as fixed effects
herb_umbs <- within(herb_umbs, growth_habit <- relevel(factor(growth_habit), ref = "Forb")) # releveling so forb is the reference
u.m3 <- zeroinfl(p_eaten ~ state + growth_habit,
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m3)
lrtest(u.m2, u.m3) # model 2

# state, growth habit, and year as fixed effects
u.m4 <- zeroinfl(p_eaten ~ state + growth_habit + as.factor(year),
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m4)
lrtest(u.m2, u.m4) # model 4

# interaction between state and growth habit as fixed effects
u.m5 <- zeroinfl(p_eaten ~ state * growth_habit,
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m5)
lrtest(u.m4, u.m5) # model 4

# interaction between state and growth habit as fixed effects, plus year
u.m6 <- zeroinfl(p_eaten ~ state * growth_habit + as.factor(year),
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m6)
lrtest(u.m4, u.m6) # almost the same, going with model 4 because its simpler

# interaction between state, growth habit, and year (year as a factor wouldn't woru - non-finite value)
u.m7 <- zeroinfl(p_eaten ~ state * growth_habit * year,
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m7)
lrtest(u.m4, u.m7) # model 4

# state and origin as fixed effects
herb_umbs <- within(herb_umbs, origin <- relevel(factor(origin), ref = "Native")) # releveling so native is the reference
u.m8 <- zeroinfl(p_eaten ~ state + origin,
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m8)
lrtest(u.m4, u.m8) # model 4

# state, origin, and year as fixed effects
u.m9 <- zeroinfl(p_eaten ~ state + origin + as.factor(year),
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m9)
lrtest(u.m4, u.m9) # model 4

# interaction between state and origin as fixed effects
u.m10 <- zeroinfl(p_eaten ~ state * origin,
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m10)
lrtest(u.m4, u.m10) # model 4

# interaction between state and origin as fixed effects, plus year
u.m11 <- zeroinfl(p_eaten ~ state * origin + as.factor(year),
                   dist = 'negbin',
                   data = herb_umbs)
summary(u.m11)
lrtest(u.m4, u.m11) # model 4
exp(-0.26760 + 0.37613*0) # 1.538119
exp(-0.26760 + 0.37613*1) # 2.24048
# effect of herbivory:
2.24048 - 1.538119 # 0.702361

## interaction between state, origin, and year - doesn't work
#u.m12 <- zeroinfl(p_eaten ~ state * origin * as.factor(year),
#                   dist = 'negbin',
#                   data = herb_umbs)
#summary(u.m12)

# state and species as fixed effects
u.m13 <- zeroinfl(p_eaten ~ state + species,
                     dist = 'negbin',
                     data = herb_umbs)
summary(u.m13)
lrtest(u.m4, u.m13) # model 4

# state, species and year as fixed effects
u.m14 <- zeroinfl(p_eaten ~ state + species + as.factor(year),
                     dist = 'negbin',
                     data = herb_umbs)
summary(u.m14)
lrtest(u.m4, u.m14) # model 14
# calculating effect size - accounting for log link
exp(-0.40972 + 0.26343*0) # 0.6638361
exp(-0.40972 + 0.26343*1) # 0.8639071
# effect of herbivory:
0.8639071 - 0.6638361 # 0.200071

# interaction between state and species as fixed effects, plus year
u.m15 <- zeroinfl(p_eaten ~ state * species + as.factor(year),
                     dist = 'negbin',
                     data = herb_umbs)
summary(u.m15)
lrtest(u.m14, u.m15) # model 15 - might go with 14 because its simpler

## interaction between state, species, and year - doesn't run
#m8 <- zeroinfl(p_eaten ~ state * species * year,
#                     dist = 'negbin',
#                     data = herb_umbs)
#summary(m8)

# checking models again
lrtest(u.m2, u.m4, u.m9, u.m14) # model 14 best - with species
res.u <- AIC(u.m1, u.m2, u.m3, u.m4, u.m5, u.m6, u.m7, u.m9, u.m10, u.m11,u.m13,u.m14,u.m15)

# check dispersion - chose lowest loglik model for example
E <- resid(u.m14, type = "pearson")
N  <- nrow(herb_umbs)
p  <- length(coef(u.m14)) + 1 # '+1' is due to theta
sum(E^2) / (N - p) # pretty close to one

# pairwise comparisons
emmeans(u.m14, ~ state + species + as.factor(year))
```