---
title: "Plant Composition Diversity Plots"
author: "Moriah"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

COLLABORATORS: Phoebe Zarnetske, Mark Hammond, Pat Bills, Kara Dobson  
DATA INPUT: Plant composition diversity measures from warmX Google drive L2 folder
DATA OUTPUT: Plots of Plant composition diversity at KBS and UMBS - Rmd and PDF located in Github folder
PROJECT: warmXtrophic

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Clear all existing data
rm(list=ls())

# Load packages
library(plotrix)
library(tidyverse)
library(ggpubr)
library(hrbrthemes)

# Set working directory
#Sys.getenv("L1DIR")
L1_dir<-Sys.getenv("L1DIR")
L2_dir<-Sys.getenv("L2DIR")
#list.files(L1_dir)

# Read in data
diversity <- read.csv(file.path(L2_dir, "plant_composition/final_plant_comp_diversity_L2.csv"))
diversity <- diversity %>% select(-X) # get rid of "X" column that shows up

# making site names capital for cleaner plots - from Kara
change_site <- function(df){
  df$site[df$site == "umbs"] <- "UMBS"
  df$site[df$site == "kbs"] <- "KBS"
  return(df)
}

diversity <- change_site(diversity) # using function from above

# creating a vector with cleaned up insecticide labels for plotting - from Kara
insect_labels <- c("insects" = "Herbivory", "no_insects" = "Reduced Herbivory")

# filter data to contain the averages and std error for each site & state
sum_shannon <- diversity %>%
  group_by(site, state, year) %>%
  summarize(avg_shannon = mean(shannon, na.rm = TRUE),
            se = std.error(shannon, na.rm = TRUE))

# Order warmed and ambient so that warmed shows up first in plotting (and is default is red = warmed; blue = ambient). First make it a factor
sum_shannon$state <- as.factor(sum_shannon$state)
levels(sum_shannon$state)
# [1] "ambient" "warmed" 
sum_shannon$state <- factor(sum_shannon$state, levels(sum_shannon$state)[c(2,1)])
levels(sum_shannon$state)
# [1] "warmed"  "ambient"

sum_simpson <- diversity %>%
  group_by(site, state, year) %>%
  summarize(avg_simpson = mean(simpson, na.rm = TRUE),
            se = std.error(simpson, na.rm = TRUE))

# Order warmed and ambient so that warmed shows up first in plotting (and is default is red = warmed; blue = ambient). First make it a factor
sum_simpson$state <- as.factor(sum_simpson$state)
levels(sum_simpson$state)
# [1] "ambient" "warmed" 
sum_simpson$state <- factor(sum_simpson$state, levels(sum_simpson$state)[c(2,1)])
levels(sum_simpson$state)
# [1] "warmed"  "ambient"

sum_richness <- diversity %>%
  group_by(site, state, year) %>%
  summarize(avg_richness = mean(richness, na.rm = TRUE),
            se = std.error(richness, na.rm = TRUE))

# Order warmed and ambient so that warmed shows up first in plotting (and is default is red = warmed; blue = ambient). First make it a factor
sum_richness$state <- as.factor(sum_richness$state)
levels(sum_richness$state)
# [1] "ambient" "warmed" 
sum_richness$state <- factor(sum_richness$state, levels(sum_richness$state)[c(2,1)])
levels(sum_richness$state)
# [1] "warmed"  "ambient"

# using function from above to change site names to uppercase
diversity <- change_site(diversity) 
sum_shannon <- change_site(sum_shannon)
sum_simpson <- change_site(sum_simpson)
sum_richness <- change_site(sum_richness)

# Set ggplot2 plotting
# This code for ggplot2 sets the theme to mostly black and white 
# (Arial font, and large font, base size=24)
theme_set(theme_bw(14))
theme_update(axis.text.x = element_text(size = 13),
             axis.text.y = element_text(size = 16),
             axis.title = element_text(size=16,face="bold"))
```

```{r, echo=F}
# shannon plot
shannon_overall_plot <- function(loc) { 
  shannon_plot <- subset(diversity, site == loc)
  return(ggplot(shannon_plot, aes(x = state, y = shannon, fill=state)) +
           facet_grid(.~insecticide, labeller = as_labeller(insect_labels)) +
                 facet_grid(.~year) +
           geom_boxplot(outlier.shape=NA, alpha=0.7) +
           geom_jitter(aes(alpha=0.8, color=state, fill=state), shape=16, size=2) +
           labs(x = NULL, y = "Shannon", title = loc) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
           scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
           scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
            theme_classic())
}

shannon_overall_kbs <- shannon_overall_plot("KBS")
shannon_overall_kbs <- shannon_overall_kbs + theme(axis.text.x=element_blank())
shannon_overall_umbs <- shannon_overall_plot("UMBS")
shannon_overall_umbs <- shannon_overall_umbs + theme(axis.text.x=element_blank()) + labs(y = NULL)

# simpson plot
simpson_overall_plot <- function(loc) { 
  simpson_plot <- subset(diversity, site == loc)
  return(ggplot(simpson_plot, aes(x = state, y = simpson, fill=state)) +
           facet_grid(.~insecticide, labeller = as_labeller(insect_labels)) +
                 facet_grid(.~year) +
           geom_boxplot(outlier.shape=NA, alpha=0.7) +
           geom_jitter(aes(alpha=0.8, color=state, fill=state), shape=16, size=2) +
           labs(x = NULL, y = "Simpson", title = loc) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
           scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
           scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
           theme_classic())
}

simpson_overall_kbs <- simpson_overall_plot("KBS")
simpson_overall_kbs <- simpson_overall_kbs + theme(axis.text.x=element_blank()) + labs(title = NULL)
simpson_overall_umbs <- simpson_overall_plot("UMBS")
simpson_overall_umbs <- simpson_overall_umbs + labs(y = NULL, title = NULL) + theme(axis.text.x=element_blank())

# richness plot
richness_overall_plot <- function(loc) { 
  richness_plot <- subset(diversity, site == loc)
  return(ggplot(richness_plot, aes(x = state, y = richness, fill=state)) +
           facet_grid(.~insecticide, labeller = as_labeller(insect_labels)) +
                 facet_grid(.~year) +
           geom_boxplot(outlier.shape=NA, alpha=0.7) +
           geom_jitter(aes(alpha=0.8, color=state, fill=state), shape=16, size=2) +
           labs(x = NULL, y = "Species Richness", title = loc) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a")) +
           scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
           scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
            theme_classic())
}

richness_overall_kbs <- richness_overall_plot("KBS")
richness_overall_kbs <- richness_overall_kbs + labs(title = NULL)
richness_overall_umbs <- richness_overall_plot("UMBS")
richness_overall_umbs <- richness_overall_umbs + labs(y = NULL, title = NULL)

diversity_overall_boxplot <- ggpubr::ggarrange(shannon_overall_kbs, shannon_overall_umbs,
                          simpson_overall_kbs, simpson_overall_umbs,
                          richness_overall_kbs, richness_overall_umbs,
                          nrow = 3, ncol = 2, legend = "none")
diversity_overall_boxplot
png("plant_comp_diversity_plots_L2_all_diversity_boxplot.png", units="in", width=8, height=8, res=300)
annotate_figure(diversity_overall_boxplot,
                left = text_grob("Ecological Diversity Indices", color = "black", rot = 90),
                bottom = text_grob("Year", color = "black"))
dev.off()
```

```{r, echo=F}
# how to make the desired plots below:
# http://www.sthda.com/english/wiki/ggplot2-line-plot-quick-start-guide-r-software-and-data-visualization

# shannon plot
sum_shannon$year <- as.factor(sum_shannon$year)
shannon_overall_plot <- function(loc) { 
  shannon_plot <- subset(sum_shannon, site == loc)
  return(ggplot(shannon_plot, aes(x = year, y = avg_shannon, group = state)) +
                 geom_errorbar(aes(ymin=avg_shannon-se, ymax=avg_shannon+se), width=.1) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           labs(x = NULL, y = "Shannon", title = loc))
}

shannon_overall_kbs <- shannon_overall_plot("KBS")
shannon_overall_kbs <- shannon_overall_kbs + theme(axis.text.x=element_blank())
shannon_overall_umbs <- shannon_overall_plot("UMBS")
shannon_overall_umbs <- shannon_overall_umbs + theme(axis.text.x=element_blank()) + labs(y = NULL)

# simpson plot
sum_simpson$year <- as.factor(sum_simpson$year)
simpson_overall_plot <- function(loc) { 
  simpson_plot <- subset(sum_simpson, site == loc)
  return(ggplot(simpson_plot, aes(x = year, y = avg_simpson, group = state)) +
                 geom_errorbar(aes(ymin=avg_simpson-se, ymax=avg_simpson+se), width=.1) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           labs(x = NULL, y = "Simpson", title = loc))
}

simpson_overall_kbs <- simpson_overall_plot("KBS")
simpson_overall_kbs <- simpson_overall_kbs + theme(axis.text.x=element_blank()) + labs(title = NULL)
simpson_overall_umbs <- simpson_overall_plot("UMBS")
simpson_overall_umbs <- simpson_overall_umbs + labs(y = NULL, title = NULL) + theme(axis.text.x=element_blank())

# richness plot
sum_richness$year <- as.factor(sum_richness$year)
richness_overall_plot <- function(loc) { 
  richness_plot <- subset(sum_richness, site == loc)
  return(ggplot(richness_plot, aes(x = year, y = avg_richness, group = state)) +
                 geom_errorbar(aes(ymin=avg_richness-se, ymax=avg_richness+se), width=.1) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           labs(x = NULL, y = "Species Richness", title = loc))
}

richness_overall_kbs <- richness_overall_plot("KBS")
richness_overall_kbs <- richness_overall_kbs + labs(title = NULL)
richness_overall_umbs <- richness_overall_plot("UMBS")
richness_overall_umbs <- richness_overall_umbs + labs(y = NULL, title = NULL)

diversity_overall_line <- ggpubr::ggarrange(shannon_overall_kbs, shannon_overall_umbs,
                          simpson_overall_kbs, simpson_overall_umbs,
                          richness_overall_kbs, richness_overall_umbs,
                          nrow = 3, ncol = 2, legend = "none")
diversity_overall_line
png("plant_comp_diversity_plots_L2_all_diversity_lineplot.png", units="in", width=10, height=10, res=300)
annotate_figure(diversity_overall_line,
                left = text_grob("Ecological Diversity Indices", color = "black", rot = 90),
                bottom = text_grob("Year", color = "black"))
dev.off()
```

