---
title: "Plant Comp Plots"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

COLLABORATORS: Kara Dobson, Phoebe Zarnetske, Mark Hammond, Pat Bills 
DATA INPUT: Clean & plot plant comp csv from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: warmXtrophic 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F}
# Clear all existing data
rm(list=ls())

# Load packages
library(tidyverse)
library(plotrix)
library(ggpubr)

# Set working directory
Sys.getenv("L0DIR")
L0_dir <- Sys.getenv("L0DIR")
L1_dir <- Sys.getenv("L1DIR")
L2_dir <- Sys.getenv("L2DIR")

# Read in plant comp data and meta-data
comp_plot <- read.csv(file.path(L2_dir, "plant_composition/final_plant_comp_plot_L2.csv"))
growth_plot <- read.csv(file.path(L2_dir, "plant_composition/final_plant_comp_plot_growthhabit_L2.csv"))
origin_plot <- read.csv(file.path(L2_dir, "plant_composition/final_plant_comp_plot_origin_L2.csv"))

# Set ggplot2 plotting
# This code for ggplot2 sets the theme to mostly black and white 
# (Arial font, and large font, base size=24)
theme_set(theme_bw(14))
theme_update(axis.text.x = element_text(size = 12, angle = 90),
             axis.text.y = element_text(size = 12))
```
```{r}
# filter the data to contain the mean and std error for relabun of each site for origin
plot_avg <- comp_plot %>%
  group_by(site, state, year) %>%
  summarize(avg_plot_total = mean(plot_total_cover_year, na.rm = TRUE),
            se = std.error(plot_total_cover_year, na.rm = TRUE))

# filter the data to contain the mean and std error for relabun of each site for origin
origin_plot_avg <- origin_plot %>%
  group_by(site, state, origin, year) %>%
  summarize(avg_relabun = mean(relabun, na.rm = TRUE),
            se = std.error(relabun, na.rm = TRUE))

# filter the data to contain the mean and std error for relabun of each site for origin
growth_plot_avg <- growth_plot %>%
  group_by(site, state, growth_habit, year) %>%
  summarize(avg_relabun = mean(relabun, na.rm = TRUE),
            se = std.error(relabun, na.rm = TRUE))

# trying to add empty values for 2021 to umbs so the x-axis matches the other plots
plot_avg2 <- plot_avg
de<-data.frame("umbs", NA, "2021", NA, NA)
names(de)<-c("site","state", "year", "avg_plot_total", "se")
de$year <- as.integer(de$year)
plot_avg <- rbind(plot_avg2, de)

origin_plot_avg2 <- origin_plot_avg
de<-data.frame("umbs", NA, "Native", "2021", NA, NA)
de2<-data.frame("umbs", NA, "Exotic", "2021", NA, NA)
names(de)<-c("site","state", "origin", "year", "avg_relabun", "se")
names(de2)<-c("site","state", "origin", "year", "avg_relabun", "se")
de$year <- as.integer(de$year)
de2$year <- as.integer(de2$year)
origin_plot_avg <- rbind(origin_plot_avg2, de, de2)

growth_plot_avg2 <- growth_plot_avg
de<-data.frame("umbs", NA, "Graminoid", "2021", NA, NA)
de2<-data.frame("umbs", NA, "Forb", "2021", NA, NA)
names(de)<-c("site","state", "growth_habit", "year", "avg_relabun", "se")
names(de2)<-c("site","state", "growth_habit", "year", "avg_relabun", "se")
de$year <- as.integer(de$year)
de2$year <- as.integer(de2$year)
growth_plot_avg <- rbind(growth_plot_avg2, de, de2)
```

General Plot Level
```{r}
plot_line <- function(loc) { 
  all_plot <- subset(plot_avg, site == loc)
  return(ggplot(all_plot, aes(x = year, y = avg_plot_total, group = state)) +
                 geom_errorbar(aes(ymin=avg_plot_total-se, ymax=avg_plot_total+se), position=position_dodge(0.1), width=.25) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a"), labels=c("Ambient","Warmed")) +
           labs(x = NULL, y = "Averegae Relative Abundance", title=loc, color="Treatment") +
                 ylim(200, 1250))
}

plot_line_kbs <- plot_line("kbs")
plot_line_kbs <- plot_line_kbs + labs(title="KBS", y=NULL) + theme(axis.text.x=element_blank())
plot_line_umbs <- plot_line("umbs")
plot_line_umbs <- plot_line_umbs + labs(title="UMBS", y=NULL)

plot_line <- ggpubr::ggarrange(plot_line_kbs, plot_line_umbs,
                          nrow = 2, ncol = 1, common.legend = T, legend="bottom")
png("total_percent_cover_plots_L2.png", units="in", width=9, height=8, res=300)
annotate_figure(plot_line,
                left = text_grob("Average Total Percent Cover", color = "black", rot = 90, size=15),
                bottom = text_grob("Year", color = "black", size=15))
dev.off()
```


Origin - Native vs. Exotic
```{r}
native <- origin_plot_avg[which(origin_plot_avg$origin == "Native"),]
exotic <- origin_plot_avg[which(origin_plot_avg$origin == "Exotic"),]

native_line <- function(loc) { 
  native_plot <- subset(native, site == loc)
  return(ggplot(native_plot, aes(x = year, y = avg_relabun, group = state)) +
                 geom_errorbar(aes(ymin=avg_relabun-se, ymax=avg_relabun+se), position=position_dodge(0.1), width=.25) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a"), labels=c("Ambient","Warmed")) +
           labs(x = NULL, y = "Averegae Relative Abundance", title=loc, color="Treatment") +
                 ylim(0,0.75))
}

native_line_kbs <- native_line("kbs")
native_line_kbs <- native_line_kbs + labs(title="KBS", subtitle= "Native", y=NULL) + theme(axis.text.x=element_blank())
native_line_umbs <- native_line("umbs")
native_line_umbs <- native_line_umbs + labs(title="UMBS", subtitle= "Native", y=NULL)

#native_line <- ggpubr::ggarrange(native_line_kbs, native_line_umbs,
#                          nrow = 2, ncol = 1, common.legend = T, legend="bottom")
#png("native_plots_L2.png", units="in", width=9, height=8, res=300)
#annotate_figure(native_line,
#                left = text_grob("Average Relative Abundance", color = "black", rot = 90, size=15),
#                bottom = text_grob("Year", color = "black", size=15))
#dev.off()

exotic_line <- function(loc) { 
  exotic_plot <- subset(exotic, site == loc)
  return(ggplot(exotic_plot, aes(x = year, y = avg_relabun, group = state)) +
                 geom_errorbar(aes(ymin=avg_relabun-se, ymax=avg_relabun+se), position=position_dodge(0.1), width=.25) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a"), labels=c("Ambient","Warmed")) +
           labs(x = NULL, y = "Averegae Relative Abundance", title=loc, color="Treatment") +
                 ylim(0,0.75))
}

exotic_line_kbs <- exotic_line("kbs")
exotic_line_kbs <- exotic_line_kbs + labs(title="KBS", subtitle="Exotic", y=NULL) + theme(axis.text.x=element_blank())
exotic_line_umbs <- exotic_line("umbs")
exotic_line_umbs <- exotic_line_umbs + labs(title="UMBS", subtitle="Exotic", y=NULL)

origin_line <- ggpubr::ggarrange(native_line_kbs, exotic_line_kbs,
                                 native_line_umbs, exotic_line_umbs,
                          nrow = 2, ncol = 2, common.legend = T, legend="bottom")
png("origin_relative_abundance_plots_L2.png", units="in", width=9, height=8, res=300)
annotate_figure(origin_line,
                left = text_grob("Average Relative Abundance", color = "black", rot = 90, size=15),
                bottom = text_grob("Year", color = "black", size=15))
dev.off()
```
Growth Habit - Forbs vs. Graminoids
```{r}
forb <- growth_plot_avg[which(growth_plot_avg$growth_habit == "Forb"),]
graminoid <- growth_plot_avg[which(growth_plot_avg$growth_habit == "Graminoid"),]

forb_line <- function(loc) { 
  forb_plot <- subset(forb, site == loc)
  return(ggplot(forb_plot, aes(x = year, y = avg_relabun, group = state)) +
                 geom_errorbar(aes(ymin=avg_relabun-se, ymax=avg_relabun+se), position=position_dodge(0.1), width=.25) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a"), labels=c("Ambient","Warmed")) +
           labs(x = NULL, y = "Averegae Relative Abundance", title=loc, color="Treatment") +
                 ylim(0.1,0.85))
}

forb_line_kbs <- forb_line("kbs")
forb_line_kbs <- forb_line_kbs + labs(title="KBS", subtitle= "Forb", y=NULL) + theme(axis.text.x=element_blank())
forb_line_umbs <- forb_line("umbs")
forb_line_umbs <- forb_line_umbs + labs(title="UMBS", subtitle= "Forb", y=NULL)

#forb_line <- ggpubr::ggarrange(forb_line_kbs, forb_line_umbs,
#                          nrow = 2, ncol = 1, common.legend = T, legend="bottom")
#png("forb_plots_L2.png", units="in", width=9, height=8, res=300)
#annotate_figure(forb_line,
#                left = text_grob("Average Relative Abundance", color = "black", rot = 90, size=15),
#                bottom = text_grob("Year", color = "black", size=15))
#dev.off()

graminoid_line <- function(loc) { 
  graminoid_plot <- subset(graminoid, site == loc)
  return(ggplot(graminoid_plot, aes(x = year, y = avg_relabun, group = state)) +
                 geom_errorbar(aes(ymin=avg_relabun-se, ymax=avg_relabun+se), position=position_dodge(0.1), width=.25) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a"), labels=c("Ambient","Warmed")) +
           labs(x = NULL, y = "Averegae Relative Abundance", title=loc, color="Treatment") +
                 ylim(0.1,0.85))
}

graminoid_line_kbs <- graminoid_line("kbs")
graminoid_line_kbs <- graminoid_line_kbs + labs(title="KBS", subtitle="Graminoid", y=NULL) + theme(axis.text.x=element_blank())
graminoid_line_umbs <- graminoid_line("umbs")
graminoid_line_umbs <- graminoid_line_umbs + labs(title="UMBS", subtitle="Graminoid", y=NULL)

growthhabit_line <- ggpubr::ggarrange(forb_line_kbs, graminoid_line_kbs,
                                    forb_line_umbs, graminoid_line_umbs,
                          nrow = 2, ncol = 2, common.legend = T, legend="bottom")
png("growthhabit_relative_abundance_plots_L2.png", units="in", width=9, height=8, res=300)
annotate_figure(growthhabit_line,
                left = text_grob("Average Relative Abundance", color = "black", rot = 90, size=15),
                bottom = text_grob("Year", color = "black", size=15))
dev.off()
```
Origin - Native vs. Exotic (ignore this chumk)
```{r}
origin_line <- function(loc) { 
  origin_plot <- subset(origin_plot_avg, site == loc)
  return(ggplot(origin_plot, aes(x = year, y = avg_relabun, group=interaction(state, origin))) +
                 geom_errorbar(aes(ymin=avg_relabun-se, ymax=avg_relabun+se), position=position_dodge(0.1), width=.25) +
           geom_line(aes(color=state), size = 1) +
           geom_point(aes(color=state), size = 2) +
           scale_color_manual(values = c("#a6bddb", "#fb6a4a"), labels=c("Ambient","Warmed")) +
           labs(x = NULL, y = "Averegae Relative Abundance", title=loc, color="Treatment"))
           #ylim(150,205))
}

origin_line_kbs <- origin_line("kbs")
origin_line_kbs <- origin_line_kbs + labs(title="KBS", y=NULL) + theme(axis.text.x=element_blank())
origin_line_umbs <- origin_line("umbs")
origin_line_umbs <- origin_line_umbs + labs(title="UMBS", y=NULL)

origin_line <- ggpubr::ggarrange(origin_line_kbs, origin_line_umbs,
                          nrow = 2, ncol = 1, common.legend = T, legend="bottom")

annotate_figure(origin_line,
                left = text_grob("Average Relative Abundance", color = "black", rot = 90, size=15),
                bottom = text_grob("Year", color = "black", size=15))

```
