---
title: "warmXtrophic Project: Plant Composition Data Wrangling"
author: "Kara Dobson, Moriah Young, Pat Bills"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(ggplot2)

# Set working directory
Sys.getenv("L1DIR")
L0_dir <- Sys.getenv("L0DIR")
L1_dir <- Sys.getenv("L1DIR")
L2_dir <- Sys.getenv("L2DIR")
list.files(L1_dir)

# read in plant comp data
comp <- read.csv(file.path(L1_dir, "plant_composition/final_plantcomp_species_removed_L1.csv"))

# delete 2021 UMBS data from dataframe 
comp <- comp[-which(comp$year == "2021" & comp$site == "umbs"),]

# read in meta data
meta <- read.csv(file.path(L0_dir, "plot.csv")) # dataframe above already has meta data in it
taxon <- read.csv(file.path(L0_dir, "taxon.csv"))
taxon <- taxon %>% select(-c(old_name, old_code, site, note1, note2, rhizomatous, MH_rhizomatous_suggestion)) # get rid of columns that arent necessary
names(taxon)[names(taxon) == "code"] <- "species" # change "code" column name to "species" so this can be merged with another dateframe below
```

```{r}
# adding sequential year variable starting at 1: this is because the years (e.g. 2015, 2016, etc) are large numbers compared with other values in the dataset. We can always label axes with these real years.
comp$year_factor[comp$year == 2015] <- 1
comp$year_factor[comp$year == 2016] <- 2
comp$year_factor[comp$year == 2017] <- 3
comp$year_factor[comp$year == 2018] <- 4
comp$year_factor[comp$year == 2019] <- 5
comp$year_factor[comp$year == 2020] <- 6
comp$year_factor[comp$year == 2021] <- 7

comp$year_factor <- as.factor(comp$year_factor)

str(comp)

```

Peak biomass
```{r}
# select peak biomass dates 
# select for all June dates
june_comp <- dplyr::filter(comp, month %in% c(6)) 
june_comp$date <- as.Date(june_comp$date)
unique(june_comp$date)
str(june_comp)
#june_comp1 <- dplyr::select(june_comp, date %in% -c("2016-06-02", "2019-06-01", "2019-06-04", "2019-06-07", #"2019-06-10", "2019-06-13", "2019-06-16")) 
#unique(june_comp1$date)
# need to be deleted:
# "2016-06-02" "2019-06-01" "2019-06-04" "2019-06-07" "2019-06-10" "2019-06-13" "2019-06-16"

# select the max date in the month per year
june_comp1 <- june_comp %>% group_by(site, year, month) %>% slice_max(julian)
unique(june_comp1$date)

# select for all July dates
july_comp <- dplyr::filter(comp, month %in% c(7))
july_comp$date <- as.Date(july_comp$date)
unique(july_comp$date)
july_comp1 <- july_comp %>% group_by(site, year, month) %>% slice_max(julian)
unique(july_comp1$date)

# select for all August dates
august_comp <- dplyr::filter(comp, month %in% c(8))
august_comp$date <- as.Date(august_comp$date)
unique(august_comp$date)
august_comp1 <- august_comp %>% group_by(site, year, month) %>% slice_max(julian)
unique(august_comp1$date)

# merge the june, july, and august data frames together
peak_comp <- full_join(august_comp1, july_comp1, by = c("site", "plot", "species", "cover", "date", "julian", "year", "month", "treatment_key", "state", "insecticide", "scientific_name", "common_name", "USDA_code", "LTER_code", "origin", "group", "family", "duration", "growth_habit", "year_factor"))

peak_comp <- full_join(peak_comp, june_comp1, by = c("site", "plot", "species", "cover", "date", "julian", "year", "month", "treatment_key", "state", "insecticide", "scientific_name", "common_name", "USDA_code", "LTER_code", "origin", "group", "family", "duration", "growth_habit", "year_factor"))
```

```{r}
peak_comp1 <- peak_comp %>% 
        select(species, site, year_factor, month, date, year, julian, plot, cover, state, insecticide)
peak_comp1$cover <- as.numeric(as.character(peak_comp1$cover))

# first get summed cover for all plants per plot
plot_cover_total = aggregate(cover ~ plot*year_factor*year*date*month*site*state*insecticide, data = peak_comp1, FUN = sum, na.rm = T)
names(plot_cover_total)[names(plot_cover_total) == "cover"] <- "plot_cover_total"
peak_comp2 <- merge(peak_comp1, plot_cover_total, by = c("plot","year_factor", "year", "date", "month", "site", "state", "insecticide"))

#calculate absolute percent cover per species in each plot
peak_comp2$absolute <- peak_comp2$cover/100

#calculate relative percent cover per species in each plot
peak_comp2$relative <- peak_comp2$cover/peak_comp2$plot_cover_total

write.csv(peak_comp2, file.path(L2_dir, "plant_composition/final_plant_comp_species_L2.csv"), row.names = F)
```

Origin
```{r}
origin_comp <- peak_comp %>% 
        select(species, site, year_factor, month, date, year, julian, plot, cover, state, insecticide, origin)
origin_comp$cover <- as.numeric(as.character(origin_comp$cover))

# first get summed cover for all plants per plot
origin_cover_total = aggregate(cover ~ plot*year_factor*year*date*month*site*state*insecticide*origin, data = origin_comp, FUN = sum, na.rm = T)
names(origin_cover_total)[names(origin_cover_total) == "cover"] <- "origin_cover_total"

origin_cover_total1 <- merge(origin_cover_total, plot_cover_total, by = c("plot","year_factor", "year", "date", "month", "site", "state", "insecticide"))

#calculate relative percent cover
origin_cover_total1$relative <- origin_cover_total1$origin_cover_total/origin_cover_total1$plot_cover_total

# subset data to just include forbs and graminoids
origin_cover_total1 <- subset(origin_cover_total1, origin == "Exotic" | origin == "Native")

write.csv(origin_cover_total1, file.path(L2_dir, "plant_composition/final_plant_comp_origin_L2.csv"), row.names = F)
```

Growth Habit
```{r}
growth_comp <- peak_comp %>% 
        select(species, site, year_factor, month, date, year, julian, plot, cover, state, insecticide, growth_habit)
growth_comp$cover <- as.numeric(as.character(growth_comp$cover))

# first get summed cover for all plants per plot
growth_cover_total = aggregate(cover ~ plot*year_factor*year*date*month*site*state*insecticide*growth_habit, data = growth_comp, FUN = sum, na.rm = T)
names(growth_cover_total)[names(growth_cover_total) == "cover"] <- "growth_cover_total"

growth_cover_total1 <- merge(growth_cover_total, plot_cover_total, by = c("plot","year_factor", "year", "date", "month", "site", "state", "insecticide"))

#calculate relative percent cover
growth_cover_total1$relative <- growth_cover_total1$growth_cover_total/growth_cover_total1$plot_cover_total

# subset data to just include forbs and graminoids
growth_cover_total1 <- subset(growth_cover_total1, growth_habit == "Forb" | growth_habit == "Graminoid")

write.csv(growth_cover_total1, file.path(L2_dir, "plant_composition/final_plant_comp_growth_habit_L2.csv"), row.names = F)
```

```{r}
august_comp1 <- august_comp %>% 
        select(species, site, year_factor, month, date, year, julian, plot, cover, state, insecticide)
august_comp1$cover <- as.numeric(as.character(august_comp1$cover))

# first get summed cover for all plants per plot
plot_cover_total = aggregate(cover ~ plot*year_factor*month*site*state*insecticide, data = august_comp1, FUN = sum, na.rm = T)
names(plot_cover_total)[names(plot_cover_total) == "cover"] <- "plot_cover_total"
View(plot_cover_total)
august_comp2 <- merge(august_comp1, plot_cover_total, by = c("plot","year_factor","site", "state", "insecticide"))

#calculate absolute percent cover per species in each plot
august_comp2$absolute <- august_comp2$cover/100

#calculate relative percent cover per species in each plot
august_comp2$relative <- august_comp2$cover/august_comp2$plot_cover_total

#write.csv(comp4, file.path(L2_dir, "plant_composition/final_plant_comp_species_L2.csv"), row.names = F)
```


######### old code below ############

Calculating Absolute Abundance
```{r}
comp1 <- comp %>% 
        select(species, site, year_factor, plot, cover, state, insecticide)
comp1$cover <- as.numeric(as.character(comp1$cover))

# calculate plot cover mean by species-plot per year - this gives the average percent cover of a species in a plot for each year
plot_mean <- aggregate(cover ~ plot*species*year_factor*site*state*insecticide, data = comp1, FUN = mean, na.rm = T)
names(plot_mean)[names(plot_mean) == "cover"] <- "plot_mean" # change "cover" column name to "plot_mean"
#View(plot_mean)

# first get summed cover for all plants per plot
plot_cover_total = aggregate(plot_mean ~ plot*year_factor*site*state*insecticide, data = plot_mean, FUN = sum, na.rm = T)
names(plot_cover_total)[names(plot_cover_total) == "plot_mean"] <- "plot_cover_total"
View(plot_cover_total)
comp2 <- merge(plot_mean, plot_cover_total, by = c("plot","year_factor","site", "state", "insecticide"))

#calculate absolute percent cover per species in each quadrat (="relative abundance")
comp2$absolute <- comp2$plot_mean/100

```

Calculating Relative Abundance
```{r}
#calculate relative percent cover per species in each quadrat (="relative abundance")
comp2$relabun <- comp2$plot_mean/comp2$plot_cover_total

# add meta data, need "growth_habit" and "origin" info
comp3 <- merge(comp2, taxon, by = c("species"))
comp4 <- comp3 %>% 
        select(species, site, year_factor, plot, state, insecticide, growth_habit, origin, plot_mean, plot_cover_total, absolute, relabun)

# write a new csv with relative and absolute abundance values at the SPECIES LEVEL and upload to the shared google drive for both sites
write.csv(comp4, file.path(L2_dir, "plant_composition/final_plant_comp_species_L2.csv"), row.names = F)
```

Plot Level Composition
```{r}
comp$date <- as.Date(as.character(comp$date))
comp$cover <- as.numeric(as.character(comp$cover))

# calculate plot cover totals for each date that data was collected 
plot_total_date <- aggregate(cover ~ plot*date*year_factor*year*site*state*insecticide, data = comp, FUN = sum, na.rm = T)
names(plot_total_date)[names(plot_total_date) == "cover"] <- "plot_total_cover_date" # change "cover" column name to "plot_total_cover"
#View(plot_total_date)

# calculate plot cover total averages across each year using the data frame created above
plot_total_avg_year <- aggregate(plot_total_cover_date ~ plot*year_factor*year*site*state*insecticide, data = plot_total_date, FUN = mean, na.rm = T)
names(plot_total_avg_year)[names(plot_total_avg_year) == "plot_total_cover_date"] <- "plot_cover_avg_year" # change "cover" column name to "plot_total_avg"
#View(plot_total_avg_year)

# calculate plot cover total (not avg) across each year using the data frame created above
plot_total_sum_year <- aggregate(plot_total_cover_date ~ plot*year_factor*year*site*state*insecticide, data = plot_total_date, FUN = sum, na.rm = T)
names(plot_total_sum_year)[names(plot_total_sum_year) == "plot_total_cover_date"] <- "plot_total_cover_year" # change "cover" column name to "plot_total_avg"
#View(plot_total_sum_year)

plot <- merge(plot_total_sum_year, plot_total_avg_year, by = c("plot", "year_factor", "year", "site", "insecticide", "state"))

# write a new csv with avg total plant comp values at the PLOT LEVEL and upload to the shared google drive for both sites
write.csv(plot, file.path(L2_dir, "plant_composition/final_plant_comp_plot_L2.csv"), row.names = F)
```

Plot Level Composition for Native and Exotic
```{r}
# calculate plot cover totals for each date that data was collected 
plot_total_origin <- aggregate(cover ~ plot*date*year_factor*year*site*state*insecticide*origin, data = comp, FUN = sum, na.rm = T)
names(plot_total_origin)[names(plot_total_origin) == "cover"] <- "plot_total_cover" # change "cover" column name to "plot_total_cover"
#View(plot_total_origin)

# calculate plot cover total averages across each year using the data frame created above
plot_total_avg_origin <- aggregate(plot_total_cover ~ plot*year_factor*year*site*state*insecticide*origin, data = plot_total_origin, FUN = mean, na.rm = T)
names(plot_total_avg_origin)[names(plot_total_avg_origin) == "plot_total_cover"] <- "plot_cover_avg" # change "cover" column name to "plot_total_avg"
#View(plot_total_avg_origin)

# calculate plot cover total SUM across each year 
plot_total_sum_year_origin <- aggregate(plot_total_cover ~ plot*year_factor*year*site*state*insecticide*origin, data = plot_total_origin, FUN = sum, na.rm = T)
names(plot_total_sum_year_origin)[names(plot_total_sum_year_origin) == "plot_total_cover"] <- "plot_cover_sum_year" # change "cover" column name to "plot_cover_sum_year"
#View(plot_total_sum_year_origin)

# this will make it so that we have total origin group cover in one column and total cover for the plot in another column - then we can calculate relative cover over the year
origin_plot <- merge(plot_total_sum_year_origin, plot_total_sum_year, by = c("plot", "year_factor", "year", "site", "insecticide", "state"))

#calculate relative abundance
origin_plot$relabun <- origin_plot$plot_cover_sum_year/origin_plot$plot_total_cover_year

origin_plot1 <- merge(origin_plot, plot_total_avg_origin, by = c("plot", "year_factor", "year", "site", "insecticide", "state", "origin"))

# We want only native and exotic data 
origin_plot2 <- origin_plot[which(origin_plot$origin == c("Native", "Exotic")),]

# write a new csv with PLOT LEVEL data and upload to the shared google drive for both sites
write.csv(origin_plot2, file.path(L2_dir, "plant_composition/final_plant_comp_plot_origin_L2.csv"), row.names = F)
```

Plot Level Composition for Growth Habit
```{r}
# calculate plot cover totals for each date that data was collected 
plot_total_growth <- aggregate(cover ~ plot*date*year_factor*year*site*state*insecticide*growth_habit, data = comp, FUN = sum, na.rm = T)
names(plot_total_growth)[names(plot_total_growth) == "cover"] <- "plot_total_cover" # change "cover" column name to "plot_total_cover"
#View(plot_total_growth)

# calculate plot cover total averages across each year using the data frame created above
plot_total_avg_growth <- aggregate(plot_total_cover ~ plot*year_factor*year*site*state*insecticide*growth_habit, data = plot_total_growth, FUN = mean, na.rm = T)
names(plot_total_avg_growth)[names(plot_total_avg_growth) == "plot_total_cover"] <- "plot_cover_avg" # change "cover" column name to "plot_total_avg"
#View(plot_total_avg_growth)

# calculate plot cover total SUM across each year using the data frame created above
plot_total_sum_year_growth <- aggregate(plot_total_cover ~ plot*year_factor*year*site*state*insecticide*growth_habit, data = plot_total_growth, FUN = sum, na.rm = T)
names(plot_total_sum_year_growth)[names(plot_total_sum_year_growth) == "plot_total_cover"] <- "plot_cover_sum_year" # change "cover" column name to "plot_total_avg"
#View(plot_total_sum_year_growth)

# this will make it so that we have total functional group cover in one column and total cover for the plot in another column - then we can calculate relative cover over the year
growth_plot <- merge(plot_total_sum_year_growth, plot_total_sum_year, by = c("plot", "year_factor", "year", "site", "insecticide", "state"))

#calculate relative abundance
growth_plot$relabun <- growth_plot$plot_cover_sum_year/growth_plot$plot_total_cover_year

growth_plot1 <- merge(growth_plot, plot_total_avg_growth, by = c("plot", "year_factor", "year", "site", "insecticide", "state", "growth_habit"))

# We want only forb and graminoid data 
growth_plot2 <- growth_plot1[which(growth_plot1$growth_habit == c("Forb", "Graminoid")),]

# write a new csv with plant comp values at the PLOT LEVEL and upload to the shared google drive for both sites
write.csv(growth_plot2, file.path(L2_dir, "plant_composition/final_plant_comp_plot_growthhabit_L2.csv"), row.names = F)
```

