---
title: "warmXtrophic Project: Plant Composition Data Analyses"
author: "Kara Dobson, Moriah Young, Pat Bills"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

# Load in packages & data
```{r, message = F}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(ggplot2)
library(lme4)
library(olsrr)
library(predictmeans)
library(car)
library(fitdistrplus)
library(ggpubr)
library(rstatix)
library(vegan)
library(interactions)
library(sjPlot)
library(effects)
library(glmmTMB)
library(labdsv) # used with Vegan package, the matrify() and matrify2() functions
library(agricolae) # HSD.test() function

# Set working directory
Sys.getenv("L1DIR")
L0_dir <- Sys.getenv("L0DIR")
L1_dir <- Sys.getenv("L1DIR")
L2_dir <- Sys.getenv("L2DIR")
list.files(L1_dir)

# read in plant comp data
comp <- read.csv(file.path(L1_dir, "plant_composition/final_plantcomp_L1.csv"))
comp <- comp %>% select(-X) # get rid of "X" column that shows up

# read in meta data
meta <- read.csv(file.path(L0_dir, "plot.csv")) # dataframe above already has meta data in it
```


```{r}
# adding sequential year variable starting at 1: this is because the years (e.g. 2015, 2016, etc) are large numbers compared with other values in the dataset. We can always label axes with these real years.
comp$year_factor[comp$year == 2015] <- 1
comp$year_factor[comp$year == 2016] <- 2
comp$year_factor[comp$year == 2017] <- 3
comp$year_factor[comp$year == 2018] <- 4
comp$year_factor[comp$year == 2019] <- 5
comp$year_factor[comp$year == 2020] <- 6
comp$year_factor[comp$year == 2021] <- 7

# Remove non-plant data
comp <- comp[!(comp$species=="Bare_Ground" | 
                       comp$species=="Unknown" | 
                       comp$species=="Brown" | 
                       comp$species=="Litter" | 
                       comp$species=="Vert_Litter" | 
                       comp$species=="Animal_Disturbance"), ]

```

Calculating Absolute Abundance
```{r}
# calculating total composition sums - proxy for most common species
# comp_yearly_totals <- comp %>%
#         group_by(site, year, plot, species) %>%
#         summarize(comp_sum = sum(cover, na.rm = T))

comp1 <- comp %>% 
        select(species, site, year_factor, plot, cover, state, insecticide, growth_habit, origin)
comp1$cover <- as.numeric(as.character(comp1$cover))

# calculate plot cover mean by species-plot per year
plot_mean <- aggregate(cover ~ plot*species*year_factor*site*state*insecticide*growth_habit*origin, data = comp1, FUN = mean, na.rm = T)
names(plot_mean)[names(plot_mean) == "cover"] <- "plot_mean" # change "cover" column name to "plot_mean"
View(plot_mean)

# first get summed cover for all plants per plot
plot_cover_total = aggregate(plot_mean ~ plot*year_factor*site*state*insecticide*growth_habit*origin, data = plot_mean, FUN = sum, na.rm = T)
names(plot_cover_total)[names(plot_cover_total) == "plot_mean"] <- "plot_cover_total"
View(plot_cover_total)
comp2 <- merge(plot_mean, plot_cover_total, by = c("plot","year_factor","site", "state", "insecticide", "growth_habit", "origin"))

#calculate absolute percent cover per species in each quadrat (="relative abundance")
comp2$absolute <- comp2$plot_mean/100

```

Calculating Relative Abundance
```{r}
#calculate relative percent cover per species in each quadrat (="relative abundance")
comp2$relabun <- comp2$plot_mean/comp2$plot_cover_total
summary(comp2)

# create dataframes for kbs and umbs - remember that these contain species within plots
comp_kbs <- subset(comp2, site == "kbs")
comp_umbs <- subset(comp2, site == "umbs")
```


KBS relative abundance data analyses 
```{r}
# checking for normality in raw data
hist(log(comp_kbs$relabun))
qqnorm(log(comp_kbs$relabun))
shapiro.test(log(comp_kbs$relabun))

hist(comp_kbs$relabun[comp_kbs$state == "ambient"])
hist(comp_kbs$relabun[comp_kbs$state == "warmed"])
```

```{r}
# Assumption checking
m1 <- lmer(relabun ~ state + year_factor + insecticide + (1|plot), data = comp_kbs, REML=FALSE)
# Check Assumptions:
# (1) Linearity: if covariates are not categorical
# (2) Homogeneity: Need to Check by plotting residuals vs predicted values.
plot(m1, main = "Relative Abundance")
# Homogeneity of variance is ok here (increasing variance in resids is not increasing with fitted values)
# Check for homogeneity of variances (true if p>0.05). If the result is not significant, the assumption of equal variances (homoscedasticity) is met (no significant difference between the group variances).
leveneTest(residuals(m1) ~ comp_kbs$state)
# Assumption met
leveneTest(residuals(m1) ~ comp_kbs$year_factor)
# Assumption not met
leveneTest(residuals(m1) ~ comp_kbs$insecticide)
# Assumption met
# (3) Normality of error term: need to check by histogram, QQplot of residuals, could do Kolmogorov-Smirnov test.
# Check for normal residuals
qqPlot(resid(m1), main = "Relative Abundance")
hist(residuals(m1), main = "Relative Abundance")
shapiro.test(resid(m1)) # Not normal
```

