---
title: 'warmXtrophic Project: SLA Plots'
author: "Phoebe Zarnetske"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in data
```{r, message = F}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(plotrix)
#library(plotrix)

# Set working directory to Google Drive
#setwd("/Volumes/GoogleDrive/Shared drives/SpaCE_Lab_warmXtrophic/data/")

# Read in data
# load in the data
Sys.getenv("L1DIR")
L1_dir<-Sys.getenv("L1DIR")
sla <- read.csv(file.path(L1_dir,"SLA/SLA_L1_nooutliers.csv")) # this L1 csv was made in the SLA_analyses script
#sla <- read.csv("/Volumes/GoogleDrive/Shared drives/SpaCE_Lab_warmXtrophic/data/L1/SLA/SLA_L1.csv")
unique(sla$species)
with(sla,table(sla$site,sla$species)) # doesn't work (KD)

# Set ggplot2 plotting
# This code for ggplot2 sets the theme to mostly black and white 
# (Arial font, and large font, base size=24)
theme_set(theme_bw(14))
theme_update(axis.text.x = element_text(size = 12, angle = 90),
             axis.text.y = element_text(size = 12))

# clean site labels for plotting
site_label <- c("kbs" = "KBS", "umbs" = "UMBS")

# take the plant-level mean
sla1 <- sla %>%
    group_by(plot,site,year,species,state, insecticide, plant_number) %>%
    summarize(sla = mean(sla),
              se = std.error(sla)) 
# take the species yearly treatment-level mean
sla_treatment <- sla1 %>%
    group_by(site, plot, state,year) %>%
    summarize(sla = mean(sla)) %>%    
    group_by(site,year,state) %>%
    summarize(sla_mean = mean(sla),
              se = std.error(sla)) 
# take the overall treatment-level mean
sla_treatment2 <- sla1 %>%
    group_by(site, plot, state, insecticide) %>%
    summarize(sla = mean(sla)) %>%    
    group_by(site,state, insecticide) %>%
    summarize(sla_mean = mean(sla),
              se = std.error(sla)) 

```

# SLA data
```{r}
# dot plot for warmed and insecticide
sla_treatment_kbs <- sla_treatment2 %>%
        filter(site == "kbs")
sla_treatment_umbs <- sla_treatment2 %>%
        filter(site == "umbs")
sla_kbs <- ggplot(sla_treatment_kbs, aes(x = state, y = sla_mean, fill = insecticide)) +
        #facet_wrap(.~insecticide, labeller = as_labeller(insect_labels)) +
        geom_pointrange(aes(ymin=sla_mean-se, ymax=sla_mean+se), pch=21,size=1,position=position_dodge(0.3)) +
        #geom_bar(position = "identity", stat = "identity", color = 'black') +
        #geom_errorbar(aes(ymin = carbon_mean - c_se, ymax = carbon_mean + c_se), width = 0.2,
        #        position = "identity") +
        labs(x = NULL, y = NULL, fill = "Treatment", title="KBS") +
        scale_fill_manual(name="Treatment",
                                         values = c("#FFB451", "#0b0055"),
                                         labels=c("Herbivory","Reduced Herbivory")) +
        #scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
        #                  labels = c("ambient" = "Ambient", "warmed" = "Warmed")) +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        #coord_cartesian(ylim=c(42,48)) +
        theme_classic() +
        theme(axis.text.x = element_text(size=15),
              axis.text.y = element_text(size=15),
              title = element_text(size=17),
              legend.text = element_text(size=15),
              legend.title = element_text(size=15))
sla_umbs <- ggplot(sla_treatment_umbs, aes(x = state, y = sla_mean, fill = insecticide)) +
        #facet_wrap(.~insecticide, labeller = as_labeller(insect_labels)) +
        geom_pointrange(aes(ymin=sla_mean-se, ymax=sla_mean+se), pch=21,size=1,position=position_dodge(0.3)) +
        #geom_bar(position = "identity", stat = "identity", color = 'black') +
        #geom_errorbar(aes(ymin = carbon_mean - c_se, ymax = carbon_mean + c_se), width = 0.2,
        #        position = "identity") +
        labs(x = NULL, y = NULL, fill = "Treatment", title="UMBS") +
        scale_fill_manual(name="Treatment",
                                         values = c("#FFB451", "#0b0055"),
                                         labels=c("Herbivory","Reduced Herbivory")) +
        #scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
        #                  labels = c("ambient" = "Ambient", "warmed" = "Warmed")) +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        #coord_cartesian(ylim=c(42,48)) +
        theme_classic() +
        theme(axis.text.x = element_text(size=15),
              axis.text.y = element_text(size=15),
              title = element_text(size=17),
              legend.text = element_text(size=15),
              legend.title = element_text(size=15))
sla_comb <- ggpubr::ggarrange(sla_kbs, sla_umbs,
                                     ncol = 2, common.legend = T, legend="right")
png("sla_treatmentlevel_L2.png", units="in", width=9, height=4, res=300)
annotate_figure(sla_comb,
                left = text_grob("Specific leaf area (cm^2/g)", color = "black", rot = 90, size=17))
dev.off()


# dot plot by year
sla_treatment_kbs <- sla_treatment %>%
        filter(site == "kbs")
sla_treatment_umbs <- sla_treatment %>%
        filter(site == "umbs")
sla_kbs <- ggplot(sla_treatment_kbs, aes(x = as.factor(year), y = sla_mean, fill = state)) +
        #facet_wrap(.~insecticide, labeller = as_labeller(insect_labels)) +
        geom_pointrange(aes(ymin=sla_mean-se, ymax=sla_mean+se), pch=21,size=1,position=position_dodge(0.3)) +
        #geom_bar(position = "identity", stat = "identity", color = 'black') +
        #geom_errorbar(aes(ymin = carbon_mean - c_se, ymax = carbon_mean + c_se), width = 0.2,
        #        position = "identity") +
        labs(x = NULL, y = NULL, fill = "Treatment", title="KBS") +
        #scale_fill_manual(name="Treatment",
        #                                 values = c("#FFB451", "#0b0055"),
        #                                 labels=c("Herbivory","Reduced Herbivory")) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
                          labels = c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        #coord_cartesian(ylim=c(42,48)) +
        theme_classic() +
        theme(axis.text.x = element_text(size=15),
              axis.text.y = element_text(size=15),
              title = element_text(size=17),
              legend.text = element_text(size=15),
              legend.title = element_text(size=15))
sla_umbs <- ggplot(sla_treatment_umbs, aes(x = as.factor(year), y = sla_mean, fill = state)) +
        #facet_wrap(.~insecticide, labeller = as_labeller(insect_labels)) +
        geom_pointrange(aes(ymin=sla_mean-se, ymax=sla_mean+se), pch=21,size=1,position=position_dodge(0.3)) +
        #geom_bar(position = "identity", stat = "identity", color = 'black') +
        #geom_errorbar(aes(ymin = carbon_mean - c_se, ymax = carbon_mean + c_se), width = 0.2,
        #        position = "identity") +
        labs(x = NULL, y = NULL, fill = "Treatment", title="UMBS") +
        #scale_fill_manual(name="Treatment",
        #                                 values = c("#FFB451", "#0b0055"),
        #                                 labels=c("Herbivory","Reduced Herbivory")) +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
                          labels = c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        #coord_cartesian(ylim=c(42,48)) +
        theme_classic() +
        theme(axis.text.x = element_text(size=15),
              axis.text.y = element_text(size=15),
              title = element_text(size=17),
              legend.text = element_text(size=15),
              legend.title = element_text(size=15))
sla_comb <- ggpubr::ggarrange(sla_kbs, sla_umbs,
                                     ncol = 2, common.legend = T, legend="right")
png("sla_treatmentlevel_year_L2.png", units="in", width=9, height=4, res=300)
annotate_figure(sla_comb,
                left = text_grob("Specific leaf area (cm^2/g)", color = "black", rot = 90, size=17))
dev.off()


# barplot for each species at kbs and umbs (no years)
png("sla_spp_L2.png", units="in", width=8, height=4, res=300)
ggplot(sla_treatment2, aes(x = species, y = sla_mean, fill = state)) +
        facet_wrap(.~site, labeller = as_labeller(site_label)) +
        #geom_point(aes(fill=state),pch=21, size=3) +
        geom_pointrange(aes(ymin=sla_mean-se, ymax=sla_mean+se), pch=21,size=0.6,position=position_dodge(0.4)) +
        #geom_bar(position = "dodge", stat = "identity", color = 'black') +
        #geom_errorbar(aes(ymin = sla_mean - se, ymax = sla_mean + se), width = 0.2) +
        labs(x = "Species", y = "Specific leaf area (cm^2/g)", fill = "Treatment") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
                          labels = c("ambient" = "Ambient", "warmed" = "Warmed")) +
        #scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        theme_bw(14) +
        theme(panel.background = element_rect(fill = NA, color = "black")) +
        theme(axis.text=element_text(size=10),
              axis.title=element_text(size=14),
              strip.text = element_text(size = 14),
              legend.title = element_text(size=14),
              legend.text = element_text(size=12))
dev.off()

# barplot for each year at kbs and umbs
png("sla_yr_L2.png", units="in", width=7, height=4, res=300)
ggplot(sla_treatment, aes(x = year, y = sla_mean, fill = state)) +
        facet_wrap(.~site, labeller = as_labeller(site_label)) +
        geom_bar(position = "dodge", stat = "identity", color = 'black') +
        geom_errorbar(aes(ymin = sla_mean - se, ymax = sla_mean + se), width = 0.2,
                position = position_dodge(width = 0.9)) +
        labs(x = "Year", y = "Specific leaf area (cm^2/g)", fill = "Treatment") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a"),
                          labels = c("ambient" = "Ambient", "warmed" = "Warmed")) +
        scale_x_discrete(labels=c("ambient" = "Ambient", "warmed" = "Warmed")) +
        scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        theme_classic() +
        theme(panel.background = element_rect(fill = NA, color = "black")) +
        theme(axis.text=element_text(size=8),
              axis.title=element_text(size=14),
              strip.text = element_text(size = 14))
dev.off()

# old figures - boxplots
ggplot(sla, aes(x = species, y = sla, fill = state)) +
        geom_boxplot() +
        labs(x = "Species", y = "Specific Leaf Area (cm2)") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = state)) +
        scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        facet_wrap(~site)
 
#ggsave(file="L2/SLA_KBS_UMBS_allyears.pdf", width=7,height=5) 

ggplot(sla, aes(x = species, y = sla, fill = state)) +
        geom_boxplot() +
        labs(x = "Species", y = "Specific Leaf Area (cm2)") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = state)) +
        scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        facet_wrap(~site + year)
 
#ggsave(file="L2/SLA_KBS_UMBS_byyear.pdf", width=7,height=5) 

ggplot(sla, aes(x = species, y = sla, fill = state)) +
        geom_boxplot() +
        labs(x = "Year", y = "Specific Leaf Area (cm2)") +
        scale_fill_manual(values = c("#a6bddb", "#fb6a4a")) +
        scale_x_discrete(labels=c("ambient" = "A", "warmed" = "W")) +
        geom_jitter(shape=1, position=position_jitterdodge(), alpha = 0.6, aes(colour = state)) +
        scale_color_manual(values = c("ambient" = "#a6bddb", "warmed" = "#fb6a4a")) +
        facet_wrap(~year)
 
#ggsave(file="L2/SLA_KBS_UMBS_byspeciesyr.pdf", width=7,height=5) 
       
       
```

