---
title: "HOBO Data Plots"
author: "Kara Dobson"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

for (package in c("tidyverse", "plotrix")) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages("package")
    library(package, character.only=T)
  }
}
```

# Plotting HOBO data

```{r, include = FALSE}
setwd("/Volumes/GoogleDrive/Shared drives/SpaCE_Lab_warmXtrophic/data/")
KBS_1 <- read_csv("L1/HOBO_data/HOBO_paired_sensor_data/KBS/KBS_pair1_L1.csv")
KBS_2 <- read_csv("L1/HOBO_data/HOBO_paired_sensor_data/KBS/KBS_pair2_L1.csv")
KBS_3 <- read_csv("L1/HOBO_data/HOBO_paired_sensor_data/KBS/KBS_pair3_L1.csv")

test_KBS_1 <- KBS_1
test_KBS_1$month <- format(test_KBS_1$Date_Time,format="%m")
test_KBS_1$year <- format(test_KBS_1$Date_Time,format="%y")
mean_monthly_warmk1 <- aggregate( XH_warmed_air_1m ~ month + year , test_KBS_1 , mean )
mean_monthly_ambk1 <- aggregate( XH_ambient_air_1m ~ month + year, test_KBS_1, mean)
mean_monthlyk1 <- merge(mean_monthly_ambk1, mean_monthly_warmk1, by=c("month", "year"))
mean_monthly_gatherk1 <- mean_monthlyk1 %>%
  gather(key = "treatment",value="temp", -month, -year)

test_KBS_2 <- KBS_2
test_KBS_2$month <- format(test_KBS_2$Date_Time,format="%m")
test_KBS_2$year <- format(test_KBS_2$Date_Time,format="%y")
mean_monthly_warmk2 <- aggregate( XH_warmed_air_1m ~ month + year , test_KBS_2 , mean )
mean_monthly_ambk2 <- aggregate( XH_ambient_air_1m ~ month + year, test_KBS_2, mean)
mean_monthlyk2 <- merge(mean_monthly_ambk2, mean_monthly_warmk2, by=c("month", "year"))
mean_monthly_gatherk2 <- mean_monthlyk2 %>%
  gather(key = "treatment",value="temp", -month, -year)

test_KBS_3 <- KBS_3
test_KBS_3$month <- format(test_KBS_3$Date_Time,format="%m")
test_KBS_3$year <- format(test_KBS_3$Date_Time,format="%y")
mean_monthly_warmk3 <- aggregate( XH_warmed_air_1m ~ month + year , test_KBS_3 , mean )
mean_monthly_ambk3 <- aggregate( XH_ambient_air_1m ~ month + year, test_KBS_3, mean)
mean_monthlyk3 <- merge(mean_monthly_ambk3, mean_monthly_warmk3, by=c("month", "year"))
mean_monthly_gatherk3 <- mean_monthlyk3 %>%
  gather(key = "treatment",value="temp", -month, -year)


KBS <- rbind(KBS_1, KBS_2, KBS_3)
KBS_season <- KBS
KBS_season$month <- format(KBS_season$Date_Time,format="%m")
KBS_season$year <- format(KBS_season$Date_Time,format="%y")
KBS_season$hour <- format(KBS_season$Date_Time, format="%H")
KBS_season <- KBS_season %>%
  filter(month > "03") %>%
  filter(month < "09") %>%
  filter(hour > "06") %>%
  filter(hour < "20") %>%
  select(Date_Time, year, month, hour, XH_warmed_air_1m, XH_ambient_air_1m)
KBS_avg <- KBS_season %>%
  gather(key = "treatment", value = "temp", -year, -month, -hour, -Date_Time) %>%
  group_by(year, treatment) %>%
  summarize(average_temp = mean(temp, na.rm = TRUE),
            se = std.error(temp, na.rm = TRUE))
```

## This plot looks at yearly average chamber temperatures during the day for the growing season (I defined this as April-August from 7 AM - 7 PM, but this could easily be changed)
```{r, echo = FALSE, message=FALSE}
ggplot(KBS_avg, aes(x = year, y = average_temp, fill = treatment)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = average_temp - se, ymax = average_temp + se), width = 0.2,
                position = position_dodge(0.9)) +
  ylim(0, 30) +
  scale_fill_manual(values=c('grey90','grey60'))+
  theme_minimal() +
  labs(x="Year", y = "Average Temperature (째C)")
```

## These plots average the chamber temperatures for each month over all years for each treatment

### 1H sensor
```{r, echo = FALSE, message=FALSE}
ggplot(mean_monthly_gatherk1, aes(x = as.numeric(month), y = temp)) +
  geom_point(aes(col = treatment, shape = year), size = 1) +
  geom_smooth(method = "loess", aes(linetype = treatment, col = treatment), size = 1.2,
              fill = "grey90") +
  labs(x = "Month",y = "Temperature 째C") +
  theme_minimal() + 
  theme(legend.position = "bottom") +
  scale_x_discrete(limits=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"))
```

### 2H sensor
```{r, echo = FALSE, message=FALSE}
ggplot(mean_monthly_gatherk2, aes(x = as.numeric(month), y = temp)) +
  geom_point(aes(col = treatment, shape = year), size = 1) +
  geom_smooth(method = "loess", aes(linetype = treatment, col = treatment), size = 1.2,
              fill = "grey90") +
  labs(x = "Month",y = "Temperature 째C") +
  theme_minimal() + 
  theme(legend.position = "bottom") +
  scale_x_discrete(limits=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"))
```

### 3H sensor
```{r, echo = FALSE, message=FALSE}
ggplot(mean_monthly_gatherk3, aes(x = as.numeric(month), y = temp)) +
  geom_point(aes(col = treatment, shape = year), size = 1) +
  geom_smooth(method = "loess", aes(linetype = treatment, col = treatment), size = 1.2,
              fill = "grey90") +
  labs(x = "Month",y = "Temperature 째C") +
  theme_minimal() + 
  theme(legend.position = "bottom") +
  scale_x_discrete(limits=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"))
```
