---
title: "warmXtrophic Project: CN Analyses"
author: "Kara Dobson"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

# Load in packages & data
```{r, message = F}
# Clear all existing data
rm(list=ls())

#Load packages
library(tidyverse)
library(bbmle)
library(lmerTest)

# Set working directory to Google Drive
setwd("/Volumes/GoogleDrive/Shared drives/SpaCE_Lab_warmXtrophic/data/")

# Read in data
cn <- read.csv("L1/final_CN_L1.csv")

# create dataframes for kbs and umbs
cn_kbs <- subset(cn, site == "kbs")
cn_umbs <- subset(cn, site == "umbs")
```

# Check what species are measured at each site
```{r}
unique(cn_kbs$species)
unique(cn_umbs$species)
# separate dataframes for each species
cn_cest_umbs <- subset(cn_umbs, species == "Cest")
cn_popr_umbs <- subset(cn_umbs, species == "Popr")
```

\pagebreak

# Data exploration: KBS Soca
```{r}
hist(cn_kbs$carbon)
qqnorm(cn_kbs$carbon)
shapiro.test(cn_kbs$carbon)

hist(cn_kbs$nitrogen)
qqnorm(cn_kbs$nitrogen)
shapiro.test(cn_kbs$nitrogen)
```

# Data exploration: UMBS Cest
```{r}
hist(cn_cest_umbs$carbon)
qqnorm(cn_cest_umbs$carbon)
shapiro.test(cn_cest_umbs$carbon)

hist(cn_cest_umbs$nitrogen)
qqnorm(cn_cest_umbs$nitrogen)
shapiro.test(cn_cest_umbs$nitrogen)
```

# Data exploration: UMBS Popr
```{r}
hist(cn_popr_umbs$carbon)
qqnorm(cn_popr_umbs$carbon)
shapiro.test(cn_popr_umbs$carbon)

hist(cn_popr_umbs$nitrogen)
qqnorm(cn_popr_umbs$nitrogen)
shapiro.test(cn_popr_umbs$nitrogen)
```

\pagebreak

# Model comparison: KBS Soca
```{r}
# carbon
m1a <- lm(carbon ~ state, data = cn_kbs)
m1b <- lm(carbon ~ state + insecticide, data = cn_kbs)
m1c <- lmer(carbon ~ state + (1|plot), data = cn_kbs)
m1d <- lmer(carbon ~ state + insecticide + (1|plot), data = cn_kbs)
AICctab(m1a, m1b, m1c, m1d, weights = T)
summary(m1a)
summary(m1c) # plot as a random effect

# nitrogen
m2a <- lm(nitrogen ~ state, data = cn_kbs)
m2b <- lm(nitrogen ~ state + insecticide, data = cn_kbs)
m2c <- lmer(nitrogen ~ state + (1|plot), data = cn_kbs)
m2d <- lmer(nitrogen ~ state + insecticide + (1|plot), data = cn_kbs)
AICctab(m2a, m2b, m2c, m2d, weights = T)
summary(m2a)
summary(m2c) # plot as a random effect
```

# Model comparison: UMBS Cest
```{r}
# carbon
m3a <- lm(carbon ~ state, data = cn_cest_umbs)
m3b <- lm(carbon ~ state + insecticide, data = cn_cest_umbs)
m3c <- lmer(carbon ~ state + (1|plot), data = cn_cest_umbs)
m3d <- lmer(carbon ~ state + insecticide + (1|plot), data = cn_cest_umbs)
AICctab(m3a, m3b, m3c, m3d, weights = T)
summary(m3a)
summary(m3c) # plot as a random effect

# nitrogen
m4a <- lm(nitrogen ~ state, data = cn_cest_umbs)
m4b <- lm(nitrogen ~ state + insecticide, data = cn_cest_umbs)
m4c <- lmer(nitrogen ~ state + (1|plot), data = cn_cest_umbs)
m4d <- lmer(nitrogen ~ state + insecticide + (1|plot), data = cn_cest_umbs)
AICctab(m4a, m4b, m4c, m4d, weights = T)
summary(m4a)
summary(m4c) # plot as a random effect
```

# Model comparison: UMBS Popr
```{r}
# carbon
m5a <- lm(carbon ~ state, data = cn_popr_umbs)
m5b <- lm(carbon ~ state + insecticide, data = cn_popr_umbs)
m5c <- lmer(carbon ~ state + (1|plot), data = cn_popr_umbs)
m5d <- lmer(carbon ~ state + insecticide + (1|plot), data = cn_popr_umbs)
AICctab(m5a, m5b, m5c, m5d, weights = T)
summary(m5a)
summary(m5c) # plot as a random effect

# nitrogen
m6a <- lm(nitrogen ~ state, data = cn_popr_umbs)
m6b <- lm(nitrogen ~ state + insecticide, data = cn_popr_umbs)
m6c <- lmer(nitrogen ~ state + (1|plot), data = cn_popr_umbs)
m6d <- lmer(nitrogen ~ state + insecticide + (1|plot), data = cn_popr_umbs)
AICctab(m6a, m6b, m6c, m6d, weights = T)
summary(m6a)
summary(m6c) # plot as a random effect
```




